
GET https://jsonplaceholder.typicode.com/posts/1

POST https://localhost:7100/Analysis/GenerateAnalysis
Content-Type: application/json

2024-09-27T10:06:33.173 …ebAPI.Controllers.ApplicationController DBUG cfdee5176ad0a52841031fd8466c8d45              3      ApplicationController.CreateApplication(application:Application{Id:$00000000-0000-0000-0000-000000000000$, ApplicationId:$00000000-0000-0000-0000-000000000000$, Name:"SampleApp20240927.01", Description:"SampleApp20240927.01 desc", Company:"", UserEmailId:□, OwnerEmailId:"TestECDeveloper001@outlook.com", Overview:□, Policies:□, CreatedDateTime:$0001-0, locale:"en") START
2024-09-27T10:06:33.176 …ervices.Applications.ApplicationService DBUG cfdee5176ad0a52841031fd8466c8d45              4        ApplicationService.CreateApplicationAsync(emailId:"TestECDeveloper001@outlook.com", application:Application{Id:$00000000-0000-0000-0000-000000000000$, ApplicationId:$00000000-0000-0000-0000-000000000000$, Name:"SampleApp20240927.01", Description:"SampleApp20240927.01 desc", Company:"", UserEmailId:□, OwnerEmailId:"TestECDeveloper001@outlook.com", Overview:□, Policies:□, CreatedDateTime:$0001-0, locale:"en") START
2024-09-27T10:06:39.558 …ries.ApplicationCosmosAsyncRepositoryV2 DBUG cfdee5176ad0a52841031fd8466c8d45              5          ApplicationCosmosAsyncRepositoryV2.GetApplicationsByUserEmailIdAsync(emailId:"TestECDeveloper001@outlook.com") START
2024-09-27T10:06:41.246 …ries.ApplicationCosmosAsyncRepositoryV2 DBUG cfdee5176ad0a52841031fd8466c8d45              6            BaseCosmosDBDataRetriever.GetDocumentsOrderedAsync(TValue:ApplicationDocument) START
2024-09-27T10:06:41.248 …ries.ApplicationCosmosAsyncRepositoryV2 DBUG cfdee5176ad0a52841031fd8466c8d45 .052m        6             CosmosDB query for class 'ABB.EDCS.Persistence.Azure.Storage.Documents.ApplicationDocument' in database https://testbiotsdkdocdb.documents.azure.com/, collection 'app'
2024-09-27T10:06:41.249 …ries.ApplicationCosmosAsyncRepositoryV2 TRCE cfdee5176ad0a52841031fd8466c8d45 .078m        6             Query: {"query":"SELECT VALUE root FROM root WHERE (((root[\"OwnerEmailId\"] = \"TestECDeveloper001@outlook.com\") AND (root[\"Type\"] = \"application\")) AND (root[\"DeletedDateTime\"] = null))"}
2024-09-27T10:06:41.252 Diginsight.Diagnostics.$Activity         DBUG cfdee5176ad0a52841031fd8466c8d45              7              Operation.Typed FeedIterator ReadNextAsync START
2024-09-27T10:06:41.311 Diginsight.Diagnostics.$Activity         DBUG cfdee5176ad0a52841031fd8466c8d45 .119m   59m  7              Operation.Typed FeedIterator ReadNextAsync END
2024-09-27T10:06:41.314 …ries.ApplicationCosmosAsyncRepositoryV2 DBUG cfdee5176ad0a52841031fd8466c8d45 .061m        6             Query executed successfully. Retrieved 3 documents of type 'ABB.EDCS.Persistence.Azure.Storage.Documents.ApplicationDocument'.
2024-09-27T10:06:41.318 Diginsight.Diagnostics.$Activity         DBUG cfdee5176ad0a52841031fd8466c8d45              7              Operation.Typed FeedIterator ReadNextAsync START
2024-09-27T10:06:41.322 Diginsight.Diagnostics.$Activity         DBUG cfdee5176ad0a52841031fd8466c8d45 .066m    4m  7              Operation.Typed FeedIterator ReadNextAsync END
2024-09-27T10:06:41.324 …ries.ApplicationCosmosAsyncRepositoryV2 DBUG cfdee5176ad0a52841031fd8466c8d45 .051m        6             Query executed successfully. Retrieved 4 documents of type 'ABB.EDCS.Persistence.Azure.Storage.Documents.ApplicationDocument'.
2024-09-27T10:06:41.328 …ries.ApplicationCosmosAsyncRepositoryV2 DBUG cfdee5176ad0a52841031fd8466c8d45 .053m   81m  6            BaseCosmosDBDataRetriever.GetDocumentsOrderedAsync END
2024-09-27T10:06:43.824 …ries.ApplicationCosmosAsyncRepositoryV2 DBUG cfdee5176ad0a52841031fd8466c8d45 .081m 4266m  5          ApplicationCosmosAsyncRepositoryV2.GetApplicationsByUserEmailIdAsync END
2024-09-27T10:06:50.875 …ries.ApplicationCosmosAsyncRepositoryV2 DBUG cfdee5176ad0a52841031fd8466c8d45              5          ApplicationCosmosAsyncRepositoryV2.ExistsAsync(applicationName:"SampleApp20240927.01", userEmailId:"TestECDeveloper001@outlook.com") START
2024-09-27T10:06:50.879 …ries.ApplicationCosmosAsyncRepositoryV2 DBUG cfdee5176ad0a52841031fd8466c8d45 .072m        5           CosmosDB query for class 'ABB.EDCS.Persistence.Azure.Storage.Documents.ApplicationDocument' in database https://testbiotsdkdocdb.documents.azure.com/, collection 'app'
2024-09-27T10:06:50.882 …ries.ApplicationCosmosAsyncRepositoryV2 TRCE cfdee5176ad0a52841031fd8466c8d45 .057m        5           Query: {"query":"SELECT VALUE root FROM root WHERE ((((LOWER(root[\"Name\"]) = \"sampleapp20240927.01\") AND CONTAINS(root[\"Type\"], \"application\")) AND (LOWER(root[\"OwnerEmailId\"]) = \"testecdeveloper001@outlook.com\")) AND (root[\"DeletedDateTime\"] = null))"}
2024-09-27T10:06:50.935 …ries.ApplicationCosmosAsyncRepositoryV2 DBUG cfdee5176ad0a52841031fd8466c8d45 .078m   58m  5          ApplicationCosmosAsyncRepositoryV2.ExistsAsync END
2024-09-27T10:07:00.064 …ervices.Applications.ApplicationService EROR cfdee5176ad0a52841031fd8466c8d45 .482m        4         Application 'SampleApp20240927.01' already exists.
2024-09-27T10:07:00.074 …ervices.Applications.ApplicationService DBUG cfdee5176ad0a52841031fd8466c8d45 .091m 26.9s  4        ApplicationService.CreateApplicationAsync END
2024-09-27T10:07:00.078 …ebAPI.Controllers.ApplicationController EROR cfdee5176ad0a52841031fd8466c8d45 .254m        3       Error in creating the application.
2024-09-27T10:07:00.081 …ebAPI.Controllers.ApplicationController EROR cfdee5176ad0a52841031fd8466c8d45 .048m        3       The application 'SampleApp20240927.01' already exists.
2024-09-27T10:07:00.085 …ebAPI.Controllers.ApplicationController DBUG cfdee5176ad0a52841031fd8466c8d45 .051m 26.9s  3      ApplicationController.CreateApplication END


POST https://localhost:7100/Analysis/GenerateAnalysis
Content-Type: application/json

2024-09-29T07:56:43.866 …iddlewares.ABBContextCreationMiddleware DBUG 55cf14750e699f212dfbcaeddf9df77b              2    ABBContextCreationMiddleware.InvokeAsync(Method:"POST", Path:PathString{Value:"/api/applications", HasValue:True}) START
2024-09-29T07:56:43.870 …iddlewares.ABBContextCreationMiddleware DBUG 55cf14750e699f212dfbcaeddf9df77b              3      ABBContextCreationMiddleware.CreateABBContext() START
2024-09-29T07:56:43.872 …iddlewares.ABBContextCreationMiddleware DBUG 55cf14750e699f212dfbcaeddf9df77b .076m    2m  3      ABBContextCreationMiddleware.CreateABBContext END
2024-09-29T07:56:43.889 …WebAPI.Program+SdkAuthenticationHandler DBUG 55cf14750e699f212dfbcaeddf9df77b              3      SdkAuthenticationHandler.HandleAuthenticateAsync() START
2024-09-29T07:56:43.892 …WebAPI.Program+SdkAuthenticationHandler DBUG 55cf14750e699f212dfbcaeddf9df77b              4        CoreAuthenticateAsync(scheme:"Bearer") START
2024-09-29T07:56:43.904 ABB.EDCS.WebAPI.Program                  DBUG 55cf14750e699f212dfbcaeddf9df77b              5          Program.AddSdkAuthentication+OnTokenValidated() START
2024-09-29T07:56:43.908 ABB.EDCS.WebAPI.Program                  DBUG 55cf14750e699f212dfbcaeddf9df77b .109m    3m  5          Program.AddSdkAuthentication+OnTokenValidated END
2024-09-29T07:56:43.917 …WebAPI.Program+SdkAuthenticationHandler DBUG 55cf14750e699f212dfbcaeddf9df77b .096m   19m  4        CoreAuthenticateAsync => AuthenticateResult{Succeeded:True, Ticket:AuthenticationTicket{AuthenticationScheme:"Bearer", Principal:ClaimsPrincipal{Claims:…, …}, …}, …} END
2024-09-29T07:56:43.927 …WebAPI.Program+SdkAuthenticationHandler DBUG 55cf14750e699f212dfbcaeddf9df77b .097m   31m  3      SdkAuthenticationHandler.HandleAuthenticateAsync => AuthenticateResult{Succeeded:True, Ticket:AuthenticationTicket{AuthenticationScheme:"Bearer", Principal:ClaimsPrincipal{Claims:ClaimsPrincipal+<get_Claims>d__22[Claim{…}, …], …}, …}, …} END
2024-09-29T07:56:43.928 …WebAPI.Program+SdkAuthenticationHandler DBUG 55cf14750e699f212dfbcaeddf9df77b .049m        2     AuthenticationScheme: Sdk was successfully authenticated.
2024-09-29T07:56:44.297 …ebAPI.Controllers.ApplicationController DBUG 55cf14750e699f212dfbcaeddf9df77b              3      ApplicationController.CreateApplication(application:Application{…}, locale:"en") START
2024-09-29T07:56:44.306 …ctorRegistration.ActivitySourceDetector DBUG 55cf14750e699f212dfbcaeddf9df77b .190m        4         New activity source detected: ABB.EDCS.Business
2024-09-29T07:56:44.318 …ervices.Applications.ApplicationService DBUG 55cf14750e699f212dfbcaeddf9df77b              4        ApplicationService.CreateApplicationAsync(emailId:"TestECDeveloper001@outlook.com", application:Application{Id:$00000000-0000-0000-0000-000000000000$, ApplicationId:$00000000-0000-0000-0000-000000000000$, Name:"SampleApp20240929.08", Description:"SampleApp20240929.08 desc", Company:"", UserEmailId:□, OwnerEmailId:"TestECDeveloper001@outlook.com", Overview:□, Policies:□, CreatedDateTime:$0001-0, locale:"en") START
2024-09-29T07:56:46.570 …ctorRegistration.ActivitySourceDetector DBUG 55cf14750e699f212dfbcaeddf9df77b .115m        5           New activity source detected: ABB.EDCS.Persistence.Azure
2024-09-29T07:56:46.573 …ries.ApplicationCosmosAsyncRepositoryV2 DBUG 55cf14750e699f212dfbcaeddf9df77b              5          ApplicationCosmosAsyncRepositoryV2.GetApplicationsByUserEmailIdAsync(emailId:"TestECDeveloper001@outlook.com") START
2024-09-29T07:56:46.583 …ries.ApplicationCosmosAsyncRepositoryV2 DBUG 55cf14750e699f212dfbcaeddf9df77b              6            BaseCosmosDBDataRetriever.GetDocumentsOrderedAsync(TValue:ApplicationDocument) START
2024-09-29T07:56:46.595 …ries.ApplicationCosmosAsyncRepositoryV2 DBUG 55cf14750e699f212dfbcaeddf9df77b    1m        6             CosmosDB query for class 'ABB.EDCS.Persistence.Azure.Storage.Documents.ApplicationDocument' in database https://testbiotsdkdocdb.documents.azure.com/, collection 'app'
2024-09-29T07:56:46.630 …ries.ApplicationCosmosAsyncRepositoryV2 TRCE 55cf14750e699f212dfbcaeddf9df77b .093m        6             Query: {"query":"SELECT VALUE root FROM root WHERE (((root[\"OwnerEmailId\"] = \"TestECDeveloper001@outlook.com\") AND (root[\"Type\"] = \"application\")) AND (root[\"DeletedDateTime\"] = null))"}
2024-09-29T07:56:46.641 …ctorRegistration.ActivitySourceDetector DBUG 55cf14750e699f212dfbcaeddf9df77b .118m        7               New activity source detected: Azure.Cosmos.Operation
2024-09-29T07:56:46.644 Diginsight.Diagnostics.$Activity         DBUG 55cf14750e699f212dfbcaeddf9df77b              7              Operation.Typed FeedIterator ReadNextAsync START
2024-09-29T07:56:48.238 Diginsight.Diagnostics.$Activity         DBUG 55cf14750e699f212dfbcaeddf9df77b .109m 1594m  7              Operation.Typed FeedIterator ReadNextAsync END
2024-09-29T07:56:48.242 …ries.ApplicationCosmosAsyncRepositoryV2 DBUG 55cf14750e699f212dfbcaeddf9df77b .132m        6             Query executed successfully. Retrieved 6 documents of type 'ABB.EDCS.Persistence.Azure.Storage.Documents.ApplicationDocument'.
2024-09-29T07:56:48.248 Diginsight.Diagnostics.$Activity         DBUG 55cf14750e699f212dfbcaeddf9df77b              7              Operation.Typed FeedIterator ReadNextAsync START
2024-09-29T07:56:48.256 Diginsight.Diagnostics.$Activity         DBUG 55cf14750e699f212dfbcaeddf9df77b .082m    7m  7              Operation.Typed FeedIterator ReadNextAsync END
2024-09-29T07:56:48.259 …ries.ApplicationCosmosAsyncRepositoryV2 DBUG 55cf14750e699f212dfbcaeddf9df77b .077m        6             Query executed successfully. Retrieved 8 documents of type 'ABB.EDCS.Persistence.Azure.Storage.Documents.ApplicationDocument'.
2024-09-29T07:56:48.264 …ries.ApplicationCosmosAsyncRepositoryV2 DBUG 55cf14750e699f212dfbcaeddf9df77b .063m 1681m  6            BaseCosmosDBDataRetriever.GetDocumentsOrderedAsync END
2024-09-29T07:56:48.268 …ries.ApplicationCosmosAsyncRepositoryV2 DBUG 55cf14750e699f212dfbcaeddf9df77b .044m 1697m  5          ApplicationCosmosAsyncRepositoryV2.GetApplicationsByUserEmailIdAsync END
2024-09-29T07:56:48.285 …ries.ApplicationCosmosAsyncRepositoryV2 DBUG 55cf14750e699f212dfbcaeddf9df77b              5          ApplicationCosmosAsyncRepositoryV2.ExistsAsync(applicationName:"SampleApp20240929.08", userEmailId:"TestECDeveloper001@outlook.com") START
2024-09-29T07:56:48.288 …ries.ApplicationCosmosAsyncRepositoryV2 DBUG 55cf14750e699f212dfbcaeddf9df77b .087m        5           CosmosDB query for class 'ABB.EDCS.Persistence.Azure.Storage.Documents.ApplicationDocument' in database https://testbiotsdkdocdb.documents.azure.com/, collection 'app'
2024-09-29T07:56:48.298 …ries.ApplicationCosmosAsyncRepositoryV2 TRCE 55cf14750e699f212dfbcaeddf9df77b .097m        5           Query: {"query":"SELECT VALUE root FROM root WHERE ((((LOWER(root[\"Name\"]) = \"sampleapp20240929.08\") AND CONTAINS(root[\"Type\"], \"application\")) AND (LOWER(root[\"OwnerEmailId\"]) = \"testecdeveloper001@outlook.com\")) AND (root[\"DeletedDateTime\"] = null))"}
2024-09-29T07:56:48.780 …ries.ApplicationCosmosAsyncRepositoryV2 DBUG 55cf14750e699f212dfbcaeddf9df77b .104m  496m  5          ApplicationCosmosAsyncRepositoryV2.ExistsAsync END
2024-09-29T07:56:48.796 …ries.ApplicationCosmosAsyncRepositoryV2 DBUG 55cf14750e699f212dfbcaeddf9df77b              5          ApplicationCosmosAsyncRepositoryV2.GetApplicationStatusAsync(statusCode:1, locale:"en") START
2024-09-29T07:56:48.811 …ries.ApplicationCosmosAsyncRepositoryV2 DBUG 55cf14750e699f212dfbcaeddf9df77b              6            BaseCosmosDBDataRetriever.GetDocumentsOrderedAsync(TValue:ApplicationStatusDetails) START
2024-09-29T07:56:48.815 …ries.ApplicationCosmosAsyncRepositoryV2 DBUG 55cf14750e699f212dfbcaeddf9df77b .091m        6             CosmosDB query for class 'ABB.EDCS.Core.Applications.ApplicationStatusDetails' in database https://testbiotsdkdocdb.documents.azure.com/, collection 'app'
2024-09-29T07:56:48.820 …ries.ApplicationCosmosAsyncRepositoryV2 TRCE 55cf14750e699f212dfbcaeddf9df77b .091m        6             Query: {"query":"SELECT VALUE root FROM root WHERE ((root[\"Locale\"] = \"en\") AND (root[\"Type\"] = \"appstatus\"))"}
2024-09-29T07:56:48.824 Diginsight.Diagnostics.$Activity         DBUG 55cf14750e699f212dfbcaeddf9df77b              7              Operation.Typed FeedIterator ReadNextAsync START
2024-09-29T07:56:48.919 Diginsight.Diagnostics.$Activity         DBUG 55cf14750e699f212dfbcaeddf9df77b .081m   95m  7              Operation.Typed FeedIterator ReadNextAsync END
2024-09-29T07:56:48.923 …ries.ApplicationCosmosAsyncRepositoryV2 DBUG 55cf14750e699f212dfbcaeddf9df77b .066m        6             Query executed successfully. Retrieved 1 documents of type 'ABB.EDCS.Core.Applications.ApplicationStatusDetails'.
2024-09-29T07:56:48.928 …ries.ApplicationCosmosAsyncRepositoryV2 DBUG 55cf14750e699f212dfbcaeddf9df77b .088m  116m  6            BaseCosmosDBDataRetriever.GetDocumentsOrderedAsync END
2024-09-29T07:56:48.933 …ries.ApplicationCosmosAsyncRepositoryV2 DBUG 55cf14750e699f212dfbcaeddf9df77b .095m  137m  5          ApplicationCosmosAsyncRepositoryV2.GetApplicationStatusAsync END
2024-09-29T07:56:48.952 …ervices.Applications.ApplicationService DBUG 55cf14750e699f212dfbcaeddf9df77b              5          ApplicationService.RegisterApplicationAsync(applicationName:"SampleApp20240929.08", application:Application{Id:$00000000-0000-0000-0000-000000000000$, ApplicationId:$00000000-0000-0000-0000-000000000000$, Name:"SampleApp20240929.08", Description:"SampleApp20240929.08 desc", Company:"", UserEmailId:□, OwnerEmailId:"TestECDeveloper001@outlook.com", Overview:□, Policies:□, CreatedDateTime:$2024-0) START
2024-09-29T07:56:50.202 …ervices.Applications.ApplicationService DBUG 55cf14750e699f212dfbcaeddf9df77b .927m        5           Registered SampleApp20240929.08 for user 'TestECDeveloper001' with Application (Client) ID 3f1a01b9-a251-4a37-a40b-00d965b0158c.
2024-09-29T07:56:50.211 …ervices.Applications.ApplicationService DBUG 55cf14750e699f212dfbcaeddf9df77b              6            ApplicationService.PreAuthorizeClientIdAsync(appObjectId:$3f1a01b9-a251-4a37-a40b-00d965b0158c$) START
2024-09-29T07:56:51.758 …ervices.Applications.ApplicationService DBUG 55cf14750e699f212dfbcaeddf9df77b .088m 1546m  6            ApplicationService.PreAuthorizeClientIdAsync END
2024-09-29T07:56:51.761 …ervices.Applications.ApplicationService DBUG 55cf14750e699f212dfbcaeddf9df77b .064m 2810m  5          ApplicationService.RegisterApplicationAsync END
2024-09-29T07:56:51.769 …ries.ApplicationCosmosAsyncRepositoryV2 DBUG 55cf14750e699f212dfbcaeddf9df77b              5          ApplicationCosmosAsyncRepositoryV2.CreateAsync(application:Application{Id:$3f1a01b9-a251-4a37-a40b-00d965b0158c$, ApplicationId:$3f1a01b9-a251-4a37-a40b-00d965b0158c$, Name:"SampleApp20240929.08", Description:"SampleApp20240929.08 desc", Company:"", UserEmailId:□, OwnerEmailId:"TestECDeveloper001@outlook.com", Overview:□, Policies:□, CreatedDateTime:$2024-0) START
2024-09-29T07:56:51.814 …ries.ApplicationCosmosAsyncRepositoryV2 DBUG 55cf14750e699f212dfbcaeddf9df77b              6            BaseCosmosDBDataRetriever.CreateDocumentAsync(TKey:Guid, TValue:ApplicationDocument, Document:ApplicationDocument{…}) START
2024-09-29T07:56:51.818 …ries.ApplicationCosmosAsyncRepositoryV2 DBUG 55cf14750e699f212dfbcaeddf9df77b              7              CosmosDBInsert START
2024-09-29T07:56:51.819 …ries.ApplicationCosmosAsyncRepositoryV2 DBUG 55cf14750e699f212dfbcaeddf9df77b .044m        7               Executing query to create document 'ABB.EDCS.Persistence.Azure.Storage.Documents.ApplicationDocument'.
2024-09-29T07:56:51.821 Diginsight.Diagnostics.$Activity         DBUG 55cf14750e699f212dfbcaeddf9df77b              8                Operation.CreateItemAsync START
2024-09-29T07:56:51.915 Diginsight.Diagnostics.$Activity         DBUG 55cf14750e699f212dfbcaeddf9df77b .089m   93m  8                Operation.CreateItemAsync END
2024-09-29T07:56:51.919 …ries.ApplicationCosmosAsyncRepositoryV2 DBUG 55cf14750e699f212dfbcaeddf9df77b .056m  101m  7              CosmosDBInsert END
2024-09-29T07:56:51.949 …ries.ApplicationCosmosAsyncRepositoryV2 DBUG 55cf14750e699f212dfbcaeddf9df77b .077m        6             Document created with ID '3f1a01b9-a251-4a37-a40b-00d965b0158c'.
2024-09-29T07:56:51.953 …ries.ApplicationCosmosAsyncRepositoryV2 DBUG 55cf14750e699f212dfbcaeddf9df77b .063m  161m  6            BaseCosmosDBDataRetriever.CreateDocumentAsync END
2024-09-29T07:56:51.956 …ries.ApplicationCosmosAsyncRepositoryV2 DBUG 55cf14750e699f212dfbcaeddf9df77b .077m  189m  5          ApplicationCosmosAsyncRepositoryV2.CreateAsync END
2024-09-29T07:56:51.971 …ervices.Applications.ApplicationService DBUG 55cf14750e699f212dfbcaeddf9df77b              5          ApplicationService.CreateClientSecretAsync(appObjectId:$fb37785b-53dc-44a6-80e9-5ca06cfc5c82$, clientSecretDisplayName:"SampleApp20240929.08") START
2024-09-29T07:56:52.678 …ervices.Applications.ApplicationService DBUG 55cf14750e699f212dfbcaeddf9df77b .101m        5           Registered SampleApp20240929.08 for user 'TestECDeveloper001'.
2024-09-29T07:56:52.681 …ervices.Applications.ApplicationService DBUG 55cf14750e699f212dfbcaeddf9df77b .051m  710m  5          ApplicationService.CreateClientSecretAsync END
2024-09-29T07:56:52.686 …ries.ApplicationCosmosAsyncRepositoryV2 DBUG 55cf14750e699f212dfbcaeddf9df77b              5          ApplicationCosmosAsyncRepositoryV2.UpdateAsync(application:Application{Id:$3f1a01b9-a251-4a37-a40b-00d965b0158c$, ApplicationId:$3f1a01b9-a251-4a37-a40b-00d965b0158c$, Name:"SampleApp20240929.08", Description:"SampleApp20240929.08 desc", Company:"", UserEmailId:□, OwnerEmailId:"TestECDeveloper001@outlook.com", Overview:□, Policies:□, CreatedDateTime:$2024-0) START
2024-09-29T07:56:52.692 …ries.ApplicationCosmosAsyncRepositoryV2 DBUG 55cf14750e699f212dfbcaeddf9df77b              6            BaseCosmosDBDataRetriever.GetFirstDocumentOrderedAsync(TValue:ApplicationDocument) START
2024-09-29T07:56:52.693 …ries.ApplicationCosmosAsyncRepositoryV2 DBUG 55cf14750e699f212dfbcaeddf9df77b .047m        6             CosmosDB query for class 'ABB.EDCS.Persistence.Azure.Storage.Documents.ApplicationDocument' in database https://testbiotsdkdocdb.documents.azure.com/, collection 'app'
2024-09-29T07:56:52.696 …ries.ApplicationCosmosAsyncRepositoryV2 TRCE 55cf14750e699f212dfbcaeddf9df77b .067m        6             Query: {"query":"SELECT TOP 1 VALUE root FROM root WHERE (((root[\"ApplicationId\"] = \"3f1a01b9-a251-4a37-a40b-00d965b0158c\") AND (root[\"Type\"] = \"application\")) AND (root[\"DeletedDateTime\"] = null))"}
2024-09-29T07:56:52.698 Diginsight.Diagnostics.$Activity         DBUG 55cf14750e699f212dfbcaeddf9df77b              7              Operation.Typed FeedIterator ReadNextAsync START
2024-09-29T07:56:53.046 Diginsight.Diagnostics.$Activity         DBUG 55cf14750e699f212dfbcaeddf9df77b .074m  347m  7              Operation.Typed FeedIterator ReadNextAsync END
2024-09-29T07:56:53.049 …ries.ApplicationCosmosAsyncRepositoryV2 DBUG 55cf14750e699f212dfbcaeddf9df77b .161m        6             Query executed successfully. Retrieved 1 documents of type 'ABB.EDCS.Persistence.Azure.Storage.Documents.ApplicationDocument'.
2024-09-29T07:56:53.055 …ries.ApplicationCosmosAsyncRepositoryV2 DBUG 55cf14750e699f212dfbcaeddf9df77b .223m  362m  6            BaseCosmosDBDataRetriever.GetFirstDocumentOrderedAsync END
2024-09-29T07:56:57.132 …ries.ApplicationCosmosAsyncRepositoryV2 DBUG 55cf14750e699f212dfbcaeddf9df77b              6            BaseCosmosDBDataRetriever.UpdateDocumentAsync(TKey:Guid, TValue:ApplicationDocument, Document:ApplicationDocument{Id:$3f1a01b9-a251-4a37-a40b-00d965b0158c$, Type:"application", ApplicationId:$3f1a01b9-a251-4a37-a40b-00d965b0158c$, Name:"SampleApp20240929.08", Description:"SampleApp20240929.08 desc", Company:"", UserEmailId:□, OwnerEmailId:"TestECDeveloper001@outlook.com", Overview:□, Policie) START
2024-09-29T07:56:57.137 Diginsight.Diagnostics.$Activity         DBUG 55cf14750e699f212dfbcaeddf9df77b              7              Operation.ReplaceItemAsync START
2024-09-29T07:56:57.200 Diginsight.Diagnostics.$Activity         DBUG 55cf14750e699f212dfbcaeddf9df77b .093m   63m  7              Operation.ReplaceItemAsync END
2024-09-29T07:56:57.202 …ries.ApplicationCosmosAsyncRepositoryV2 DBUG 55cf14750e699f212dfbcaeddf9df77b .065m        6             Document '3f1a01b9-a251-4a37-a40b-00d965b0158c' updated successfully.
2024-09-29T07:56:57.205 …ries.ApplicationCosmosAsyncRepositoryV2 DBUG 55cf14750e699f212dfbcaeddf9df77b .055m   73m  6            BaseCosmosDBDataRetriever.UpdateDocumentAsync END
2024-09-29T07:56:57.208 …ries.ApplicationCosmosAsyncRepositoryV2 DBUG 55cf14750e699f212dfbcaeddf9df77b .065m 4522m  5          ApplicationCosmosAsyncRepositoryV2.UpdateAsync END
2024-09-29T07:56:57.210 …ervices.Applications.ApplicationService DBUG 55cf14750e699f212dfbcaeddf9df77b .046m        4         Application created successfully.
2024-09-29T07:56:58.279 …ries.ApplicationCosmosAsyncRepositoryV2 DBUG 55cf14750e699f212dfbcaeddf9df77b              5          ApplicationCosmosAsyncRepositoryV2.GrantPermissionOnPlantAsync(applicationId:$3f1a01b9-a251-4a37-a40b-00d965b0158c$, plantId:$77903d8a-ba6e-4510-b1bb-d96f415f2120$) START
2024-09-29T07:56:58.284 …ries.ApplicationCosmosAsyncRepositoryV2 DBUG 55cf14750e699f212dfbcaeddf9df77b              6            ApplicationCosmosAsyncRepositoryV2.HasPermissionOnPlantAsync(applicationId:$3f1a01b9-a251-4a37-a40b-00d965b0158c$, plantId:$77903d8a-ba6e-4510-b1bb-d96f415f2120$) START
2024-09-29T07:56:58.285 …ries.ApplicationCosmosAsyncRepositoryV2 DBUG 55cf14750e699f212dfbcaeddf9df77b .062m        6             CosmosDB query for class 'ABB.EDCS.Persistence.Azure.Storage.Documents.ApplicationGrantDocument' in database https://testbiotsdkdocdb.documents.azure.com/, collection 'app'
2024-09-29T07:56:58.287 …ries.ApplicationCosmosAsyncRepositoryV2 TRCE 55cf14750e699f212dfbcaeddf9df77b .050m        6             Query: {"query":"SELECT VALUE root FROM root WHERE ((((root[\"ApplicationId\"] = \"3f1a01b9-a251-4a37-a40b-00d965b0158c\") AND (root[\"Type\"] = \"grant-plant\")) AND ((root[\"Target\"] = \"77903d8a-ba6e-4510-b1bb-d96f415f2120\") OR (root[\"Target\"] = \"00000000-0000-0000-0000-000000000000\"))) AND (root[\"DeletedDateTime\"] = null))"}
2024-09-29T07:56:58.339 …ries.ApplicationCosmosAsyncRepositoryV2 DBUG 55cf14750e699f212dfbcaeddf9df77b .071m   55m  6            ApplicationCosmosAsyncRepositoryV2.HasPermissionOnPlantAsync END
2024-09-29T07:56:58.363 …ries.ApplicationCosmosAsyncRepositoryV2 DBUG 55cf14750e699f212dfbcaeddf9df77b              6            BaseCosmosDBDataRetriever.CreateDocumentAsync(TKey:Guid, TValue:ApplicationGrantDocument, Document:ApplicationGrantDocument{…}) START
2024-09-29T07:56:58.373 …ries.ApplicationCosmosAsyncRepositoryV2 DBUG 55cf14750e699f212dfbcaeddf9df77b              7              CosmosDBInsert START
2024-09-29T07:56:58.376 …ries.ApplicationCosmosAsyncRepositoryV2 DBUG 55cf14750e699f212dfbcaeddf9df77b .066m        7               Executing query to create document 'ABB.EDCS.Persistence.Azure.Storage.Documents.ApplicationGrantDocument'.
2024-09-29T07:56:58.380 Diginsight.Diagnostics.$Activity         DBUG 55cf14750e699f212dfbcaeddf9df77b              8                Operation.CreateItemAsync START
2024-09-29T07:56:58.449 Diginsight.Diagnostics.$Activity         DBUG 55cf14750e699f212dfbcaeddf9df77b .075m   69m  8                Operation.CreateItemAsync END
2024-09-29T07:56:58.453 …ries.ApplicationCosmosAsyncRepositoryV2 DBUG 55cf14750e699f212dfbcaeddf9df77b .047m   79m  7              CosmosDBInsert END
2024-09-29T07:56:58.456 …ries.ApplicationCosmosAsyncRepositoryV2 DBUG 55cf14750e699f212dfbcaeddf9df77b .075m        6             Document created with ID '057112f2-81a3-49a5-887f-0fc9f3906060'.
2024-09-29T07:56:58.460 …ries.ApplicationCosmosAsyncRepositoryV2 DBUG 55cf14750e699f212dfbcaeddf9df77b .049m  104m  6            BaseCosmosDBDataRetriever.CreateDocumentAsync END
2024-09-29T07:56:58.464 …ries.ApplicationCosmosAsyncRepositoryV2 DBUG 55cf14750e699f212dfbcaeddf9df77b .064m  184m  5          ApplicationCosmosAsyncRepositoryV2.GrantPermissionOnPlantAsync END
2024-09-29T07:56:58.476 …ries.ApplicationCosmosAsyncRepositoryV2 DBUG 55cf14750e699f212dfbcaeddf9df77b              5          ApplicationCosmosAsyncRepositoryV2.GrantPermissionOnPlantAsync(applicationId:$3f1a01b9-a251-4a37-a40b-00d965b0158c$, plantId:$9178e10f-96ca-4378-b11d-76b03585f9a1$) START
2024-09-29T07:56:58.487 …ries.ApplicationCosmosAsyncRepositoryV2 DBUG 55cf14750e699f212dfbcaeddf9df77b              6            ApplicationCosmosAsyncRepositoryV2.HasPermissionOnPlantAsync(applicationId:$3f1a01b9-a251-4a37-a40b-00d965b0158c$, plantId:$9178e10f-96ca-4378-b11d-76b03585f9a1$) START
2024-09-29T07:56:58.489 …ries.ApplicationCosmosAsyncRepositoryV2 DBUG 55cf14750e699f212dfbcaeddf9df77b .066m        6             CosmosDB query for class 'ABB.EDCS.Persistence.Azure.Storage.Documents.ApplicationGrantDocument' in database https://testbiotsdkdocdb.documents.azure.com/, collection 'app'
2024-09-29T07:56:58.491 …ries.ApplicationCosmosAsyncRepositoryV2 TRCE 55cf14750e699f212dfbcaeddf9df77b .046m        6             Query: {"query":"SELECT VALUE root FROM root WHERE ((((root[\"ApplicationId\"] = \"3f1a01b9-a251-4a37-a40b-00d965b0158c\") AND (root[\"Type\"] = \"grant-plant\")) AND ((root[\"Target\"] = \"9178e10f-96ca-4378-b11d-76b03585f9a1\") OR (root[\"Target\"] = \"00000000-0000-0000-0000-000000000000\"))) AND (root[\"DeletedDateTime\"] = null))"}
2024-09-29T07:56:58.616 …ries.ApplicationCosmosAsyncRepositoryV2 DBUG 55cf14750e699f212dfbcaeddf9df77b   10m  118m  6            ApplicationCosmosAsyncRepositoryV2.HasPermissionOnPlantAsync END
2024-09-29T07:56:58.640 …ries.ApplicationCosmosAsyncRepositoryV2 DBUG 55cf14750e699f212dfbcaeddf9df77b              6            BaseCosmosDBDataRetriever.CreateDocumentAsync(TKey:Guid, TValue:ApplicationGrantDocument, Document:ApplicationGrantDocument{Id:$b9c6a42e-ec1c-49c6-8b2f-deb165cb628a$, Type:"grant-plant", ApplicationId:$3f1a01b9-a251-4a37-a40b-00d965b0158c$, Target:$9178e10f-96ca-4378-b11d-76b03585f9a1$, UserEmailId:□, Prefix:□, Hash:□, PrimaryKey:□, SecondaryKey:□, SubscriptionStatus:□, SubscriptionScope:□, Creat) START
2024-09-29T07:56:58.649 …ries.ApplicationCosmosAsyncRepositoryV2 DBUG 55cf14750e699f212dfbcaeddf9df77b              7              CosmosDBInsert START
2024-09-29T07:56:58.653 …ries.ApplicationCosmosAsyncRepositoryV2 DBUG 55cf14750e699f212dfbcaeddf9df77b .363m        7               Executing query to create document 'ABB.EDCS.Persistence.Azure.Storage.Documents.ApplicationGrantDocument'.
2024-09-29T07:56:58.657 Diginsight.Diagnostics.$Activity         DBUG 55cf14750e699f212dfbcaeddf9df77b              8                Operation.CreateItemAsync START
2024-09-29T07:56:58.711 Diginsight.Diagnostics.$Activity         DBUG 55cf14750e699f212dfbcaeddf9df77b .072m   53m  8                Operation.CreateItemAsync END
2024-09-29T07:56:58.714 …ries.ApplicationCosmosAsyncRepositoryV2 DBUG 55cf14750e699f212dfbcaeddf9df77b .044m   64m  7              CosmosDBInsert END
2024-09-29T07:56:58.716 …ries.ApplicationCosmosAsyncRepositoryV2 DBUG 55cf14750e699f212dfbcaeddf9df77b .049m        6             Document created with ID 'b9c6a42e-ec1c-49c6-8b2f-deb165cb628a'.
2024-09-29T07:56:58.721 …ries.ApplicationCosmosAsyncRepositoryV2 DBUG 55cf14750e699f212dfbcaeddf9df77b    1m   79m  6            BaseCosmosDBDataRetriever.CreateDocumentAsync END
2024-09-29T07:56:58.725 …ries.ApplicationCosmosAsyncRepositoryV2 DBUG 55cf14750e699f212dfbcaeddf9df77b .065m  248m  5          ApplicationCosmosAsyncRepositoryV2.GrantPermissionOnPlantAsync END
2024-09-29T07:56:58.736 …ries.ApplicationCosmosAsyncRepositoryV2 DBUG 55cf14750e699f212dfbcaeddf9df77b              5          ApplicationCosmosAsyncRepositoryV2.GrantPermissionOnPlantAsync(applicationId:$3f1a01b9-a251-4a37-a40b-00d965b0158c$, plantId:$d9c5ae28-48fb-46ee-8f1b-98e2625a4af5$) START
2024-09-29T07:56:58.746 …ries.ApplicationCosmosAsyncRepositoryV2 DBUG 55cf14750e699f212dfbcaeddf9df77b              6            ApplicationCosmosAsyncRepositoryV2.HasPermissionOnPlantAsync(applicationId:$3f1a01b9-a251-4a37-a40b-00d965b0158c$, plantId:$d9c5ae28-48fb-46ee-8f1b-98e2625a4af5$) START
2024-09-29T07:56:58.748 …ries.ApplicationCosmosAsyncRepositoryV2 DBUG 55cf14750e699f212dfbcaeddf9df77b .073m        6             CosmosDB query for class 'ABB.EDCS.Persistence.Azure.Storage.Documents.ApplicationGrantDocument' in database https://testbiotsdkdocdb.documents.azure.com/, collection 'app'
2024-09-29T07:56:58.753 …ries.ApplicationCosmosAsyncRepositoryV2 TRCE 55cf14750e699f212dfbcaeddf9df77b .140m        6             Query: {"query":"SELECT VALUE root FROM root WHERE ((((root[\"ApplicationId\"] = \"3f1a01b9-a251-4a37-a40b-00d965b0158c\") AND (root[\"Type\"] = \"grant-plant\")) AND ((root[\"Target\"] = \"d9c5ae28-48fb-46ee-8f1b-98e2625a4af5\") OR (root[\"Target\"] = \"00000000-0000-0000-0000-000000000000\"))) AND (root[\"DeletedDateTime\"] = null))"}
2024-09-29T07:56:59.045 …ries.ApplicationCosmosAsyncRepositoryV2 DBUG 55cf14750e699f212dfbcaeddf9df77b .077m  299m  6            ApplicationCosmosAsyncRepositoryV2.HasPermissionOnPlantAsync END
2024-09-29T07:56:59.063 …ries.ApplicationCosmosAsyncRepositoryV2 DBUG 55cf14750e699f212dfbcaeddf9df77b              6            BaseCosmosDBDataRetriever.CreateDocumentAsync(TKey:Guid, TValue:ApplicationGrantDocument, Document:ApplicationGrantDocument{Id:$cbff4411-12c0-4ac0-8b3d-9503310b5dfd$, Type:"grant-plant", ApplicationId:$3f1a01b9-a251-4a37-a40b-00d965b0158c$, Target:$d9c5ae28-48fb-46ee-8f1b-98e2625a4af5$, UserEmailId:□, Prefix:□, Hash:□, PrimaryKey:□, SecondaryKey:□, SubscriptionStatus:□, SubscriptionScope:□, Creat) START
2024-09-29T07:56:59.072 …ries.ApplicationCosmosAsyncRepositoryV2 DBUG 55cf14750e699f212dfbcaeddf9df77b              7              CosmosDBInsert START
2024-09-29T07:56:59.075 …ries.ApplicationCosmosAsyncRepositoryV2 DBUG 55cf14750e699f212dfbcaeddf9df77b .061m        7               Executing query to create document 'ABB.EDCS.Persistence.Azure.Storage.Documents.ApplicationGrantDocument'.
2024-09-29T07:56:59.079 Diginsight.Diagnostics.$Activity         DBUG 55cf14750e699f212dfbcaeddf9df77b              8                Operation.CreateItemAsync START
2024-09-29T07:56:59.141 Diginsight.Diagnostics.$Activity         DBUG 55cf14750e699f212dfbcaeddf9df77b .645m   61m  8                Operation.CreateItemAsync END
2024-09-29T07:56:59.149 …ries.ApplicationCosmosAsyncRepositoryV2 DBUG 55cf14750e699f212dfbcaeddf9df77b .614m   73m  7              CosmosDBInsert END
2024-09-29T07:56:59.152 …ries.ApplicationCosmosAsyncRepositoryV2 DBUG 55cf14750e699f212dfbcaeddf9df77b .447m        6             Document created with ID 'cbff4411-12c0-4ac0-8b3d-9503310b5dfd'.
2024-09-29T07:56:59.161 …ries.ApplicationCosmosAsyncRepositoryV2 DBUG 55cf14750e699f212dfbcaeddf9df77b .907m   97m  6            BaseCosmosDBDataRetriever.CreateDocumentAsync END
2024-09-29T07:56:59.182 …ries.ApplicationCosmosAsyncRepositoryV2 DBUG 55cf14750e699f212dfbcaeddf9df77b   12m  429m  5          ApplicationCosmosAsyncRepositoryV2.GrantPermissionOnPlantAsync END
2024-09-29T07:56:59.200 …ries.ApplicationCosmosAsyncRepositoryV2 DBUG 55cf14750e699f212dfbcaeddf9df77b              5          ApplicationCosmosAsyncRepositoryV2.GrantPermissionOnPlantAsync(applicationId:$3f1a01b9-a251-4a37-a40b-00d965b0158c$, plantId:$8c951293-4632-4a95-94f4-7e1d8eca73f2$) START
2024-09-29T07:56:59.212 …ries.ApplicationCosmosAsyncRepositoryV2 DBUG 55cf14750e699f212dfbcaeddf9df77b              6            ApplicationCosmosAsyncRepositoryV2.HasPermissionOnPlantAsync(applicationId:$3f1a01b9-a251-4a37-a40b-00d965b0158c$, plantId:$8c951293-4632-4a95-94f4-7e1d8eca73f2$) START
2024-09-29T07:56:59.214 …ries.ApplicationCosmosAsyncRepositoryV2 DBUG 55cf14750e699f212dfbcaeddf9df77b .064m        6             CosmosDB query for class 'ABB.EDCS.Persistence.Azure.Storage.Documents.ApplicationGrantDocument' in database https://testbiotsdkdocdb.documents.azure.com/, collection 'app'
2024-09-29T07:56:59.217 …ries.ApplicationCosmosAsyncRepositoryV2 TRCE 55cf14750e699f212dfbcaeddf9df77b .049m        6             Query: {"query":"SELECT VALUE root FROM root WHERE ((((root[\"ApplicationId\"] = \"3f1a01b9-a251-4a37-a40b-00d965b0158c\") AND (root[\"Type\"] = \"grant-plant\")) AND ((root[\"Target\"] = \"8c951293-4632-4a95-94f4-7e1d8eca73f2\") OR (root[\"Target\"] = \"00000000-0000-0000-0000-000000000000\"))) AND (root[\"DeletedDateTime\"] = null))"}
2024-09-29T07:56:59.275 …ries.ApplicationCosmosAsyncRepositoryV2 DBUG 55cf14750e699f212dfbcaeddf9df77b .069m   62m  6            ApplicationCosmosAsyncRepositoryV2.HasPermissionOnPlantAsync END
2024-09-29T07:56:59.293 …ries.ApplicationCosmosAsyncRepositoryV2 DBUG 55cf14750e699f212dfbcaeddf9df77b              6            BaseCosmosDBDataRetriever.CreateDocumentAsync(TKey:Guid, TValue:ApplicationGrantDocument, Document:ApplicationGrantDocument{Id:$fb26cbc5-3965-42b5-a8c5-8d93d6c8d40b$, Type:"grant-plant", ApplicationId:$3f1a01b9-a251-4a37-a40b-00d965b0158c$, Target:$8c951293-4632-4a95-94f4-7e1d8eca73f2$, UserEmailId:□, Prefix:□, Hash:□, PrimaryKey:□, SecondaryKey:□, SubscriptionStatus:□, SubscriptionScope:□, Creat) START
2024-09-29T07:56:59.305 …ries.ApplicationCosmosAsyncRepositoryV2 DBUG 55cf14750e699f212dfbcaeddf9df77b              7              CosmosDBInsert START
2024-09-29T07:56:59.308 …ries.ApplicationCosmosAsyncRepositoryV2 DBUG 55cf14750e699f212dfbcaeddf9df77b .087m        7               Executing query to create document 'ABB.EDCS.Persistence.Azure.Storage.Documents.ApplicationGrantDocument'.
2024-09-29T07:56:59.314 Diginsight.Diagnostics.$Activity         DBUG 55cf14750e699f212dfbcaeddf9df77b              8                Operation.CreateItemAsync START
2024-09-29T07:56:59.373 Diginsight.Diagnostics.$Activity         DBUG 55cf14750e699f212dfbcaeddf9df77b .090m   60m  8                Operation.CreateItemAsync END
2024-09-29T07:56:59.378 …ries.ApplicationCosmosAsyncRepositoryV2 DBUG 55cf14750e699f212dfbcaeddf9df77b .129m   71m  7              CosmosDBInsert END
2024-09-29T07:56:59.380 …ries.ApplicationCosmosAsyncRepositoryV2 DBUG 55cf14750e699f212dfbcaeddf9df77b .055m        6             Document created with ID 'fb26cbc5-3965-42b5-a8c5-8d93d6c8d40b'.
2024-09-29T07:56:59.383 …ries.ApplicationCosmosAsyncRepositoryV2 DBUG 55cf14750e699f212dfbcaeddf9df77b .051m   89m  6            BaseCosmosDBDataRetriever.CreateDocumentAsync END
2024-09-29T07:56:59.386 …ries.ApplicationCosmosAsyncRepositoryV2 DBUG 55cf14750e699f212dfbcaeddf9df77b .046m  185m  5          ApplicationCosmosAsyncRepositoryV2.GrantPermissionOnPlantAsync END
2024-09-29T07:56:59.395 …ries.ApplicationCosmosAsyncRepositoryV2 DBUG 55cf14750e699f212dfbcaeddf9df77b              5          ApplicationCosmosAsyncRepositoryV2.GrantPermissionOnPlantAsync(applicationId:$3f1a01b9-a251-4a37-a40b-00d965b0158c$, plantId:$e2be68b9-501e-4381-8bb1-fb1d21ad8937$) START
2024-09-29T07:56:59.404 …ries.ApplicationCosmosAsyncRepositoryV2 DBUG 55cf14750e699f212dfbcaeddf9df77b              6            ApplicationCosmosAsyncRepositoryV2.HasPermissionOnPlantAsync(applicationId:$3f1a01b9-a251-4a37-a40b-00d965b0158c$, plantId:$e2be68b9-501e-4381-8bb1-fb1d21ad8937$) START
2024-09-29T07:56:59.406 …ries.ApplicationCosmosAsyncRepositoryV2 DBUG 55cf14750e699f212dfbcaeddf9df77b .055m        6             CosmosDB query for class 'ABB.EDCS.Persistence.Azure.Storage.Documents.ApplicationGrantDocument' in database https://testbiotsdkdocdb.documents.azure.com/, collection 'app'
2024-09-29T07:56:59.408 …ries.ApplicationCosmosAsyncRepositoryV2 TRCE 55cf14750e699f212dfbcaeddf9df77b .073m        6             Query: {"query":"SELECT VALUE root FROM root WHERE ((((root[\"ApplicationId\"] = \"3f1a01b9-a251-4a37-a40b-00d965b0158c\") AND (root[\"Type\"] = \"grant-plant\")) AND ((root[\"Target\"] = \"e2be68b9-501e-4381-8bb1-fb1d21ad8937\") OR (root[\"Target\"] = \"00000000-0000-0000-0000-000000000000\"))) AND (root[\"DeletedDateTime\"] = null))"}
2024-09-29T07:56:59.464 …ries.ApplicationCosmosAsyncRepositoryV2 DBUG 55cf14750e699f212dfbcaeddf9df77b .072m   59m  6            ApplicationCosmosAsyncRepositoryV2.HasPermissionOnPlantAsync END
2024-09-29T07:56:59.482 …ries.ApplicationCosmosAsyncRepositoryV2 DBUG 55cf14750e699f212dfbcaeddf9df77b              6            BaseCosmosDBDataRetriever.CreateDocumentAsync(TKey:Guid, TValue:ApplicationGrantDocument, Document:ApplicationGrantDocument{Id:$bbd8d5f9-312f-423a-97bd-66b6f3b2d771$, Type:"grant-plant", ApplicationId:$3f1a01b9-a251-4a37-a40b-00d965b0158c$, Target:$e2be68b9-501e-4381-8bb1-fb1d21ad8937$, UserEmailId:□, Prefix:□, Hash:□, PrimaryKey:□, SecondaryKey:□, SubscriptionStatus:□, SubscriptionScope:□, Creat) START
2024-09-29T07:56:59.493 …ries.ApplicationCosmosAsyncRepositoryV2 DBUG 55cf14750e699f212dfbcaeddf9df77b              7              CosmosDBInsert START
2024-09-29T07:56:59.495 …ries.ApplicationCosmosAsyncRepositoryV2 DBUG 55cf14750e699f212dfbcaeddf9df77b .054m        7               Executing query to create document 'ABB.EDCS.Persistence.Azure.Storage.Documents.ApplicationGrantDocument'.
2024-09-29T07:56:59.502 Diginsight.Diagnostics.$Activity         DBUG 55cf14750e699f212dfbcaeddf9df77b              8                Operation.CreateItemAsync START
2024-09-29T07:56:59.564 Diginsight.Diagnostics.$Activity         DBUG 55cf14750e699f212dfbcaeddf9df77b .099m   61m  8                Operation.CreateItemAsync END
2024-09-29T07:56:59.568 …ries.ApplicationCosmosAsyncRepositoryV2 DBUG 55cf14750e699f212dfbcaeddf9df77b .117m   74m  7              CosmosDBInsert END
2024-09-29T07:56:59.573 …ries.ApplicationCosmosAsyncRepositoryV2 DBUG 55cf14750e699f212dfbcaeddf9df77b    2m        6             Document created with ID 'bbd8d5f9-312f-423a-97bd-66b6f3b2d771'.
2024-09-29T07:56:59.583 …ries.ApplicationCosmosAsyncRepositoryV2 DBUG 55cf14750e699f212dfbcaeddf9df77b    6m   95m  6            BaseCosmosDBDataRetriever.CreateDocumentAsync END
2024-09-29T07:56:59.588 …ries.ApplicationCosmosAsyncRepositoryV2 DBUG 55cf14750e699f212dfbcaeddf9df77b    1m  192m  5          ApplicationCosmosAsyncRepositoryV2.GrantPermissionOnPlantAsync END
2024-09-29T07:56:59.601 …ries.ApplicationCosmosAsyncRepositoryV2 DBUG 55cf14750e699f212dfbcaeddf9df77b              5          ApplicationCosmosAsyncRepositoryV2.GrantPermissionOnPlantAsync(applicationId:$3f1a01b9-a251-4a37-a40b-00d965b0158c$, plantId:$54674195-7a38-4086-a856-0b2fcdc26461$) START
2024-09-29T07:56:59.612 …ries.ApplicationCosmosAsyncRepositoryV2 DBUG 55cf14750e699f212dfbcaeddf9df77b              6            ApplicationCosmosAsyncRepositoryV2.HasPermissionOnPlantAsync(applicationId:$3f1a01b9-a251-4a37-a40b-00d965b0158c$, plantId:$54674195-7a38-4086-a856-0b2fcdc26461$) START
2024-09-29T07:56:59.615 …ries.ApplicationCosmosAsyncRepositoryV2 DBUG 55cf14750e699f212dfbcaeddf9df77b .070m        6             CosmosDB query for class 'ABB.EDCS.Persistence.Azure.Storage.Documents.ApplicationGrantDocument' in database https://testbiotsdkdocdb.documents.azure.com/, collection 'app'
2024-09-29T07:56:59.617 …ries.ApplicationCosmosAsyncRepositoryV2 TRCE 55cf14750e699f212dfbcaeddf9df77b .088m        6             Query: {"query":"SELECT VALUE root FROM root WHERE ((((root[\"ApplicationId\"] = \"3f1a01b9-a251-4a37-a40b-00d965b0158c\") AND (root[\"Type\"] = \"grant-plant\")) AND ((root[\"Target\"] = \"54674195-7a38-4086-a856-0b2fcdc26461\") OR (root[\"Target\"] = \"00000000-0000-0000-0000-000000000000\"))) AND (root[\"DeletedDateTime\"] = null))"}
2024-09-29T07:56:59.669 …ries.ApplicationCosmosAsyncRepositoryV2 DBUG 55cf14750e699f212dfbcaeddf9df77b .079m   55m  6            ApplicationCosmosAsyncRepositoryV2.HasPermissionOnPlantAsync END
2024-09-29T07:56:59.682 …ries.ApplicationCosmosAsyncRepositoryV2 DBUG 55cf14750e699f212dfbcaeddf9df77b              6            BaseCosmosDBDataRetriever.CreateDocumentAsync(TKey:Guid, TValue:ApplicationGrantDocument, Document:ApplicationGrantDocument{Id:$6122bc4b-1c3e-46a3-8b33-e36eff279206$, Type:"grant-plant", ApplicationId:$3f1a01b9-a251-4a37-a40b-00d965b0158c$, Target:$54674195-7a38-4086-a856-0b2fcdc26461$, UserEmailId:□, Prefix:□, Hash:□, PrimaryKey:□, SecondaryKey:□, SubscriptionStatus:□, SubscriptionScope:□, Creat) START
2024-09-29T07:56:59.690 …ries.ApplicationCosmosAsyncRepositoryV2 DBUG 55cf14750e699f212dfbcaeddf9df77b              7              CosmosDBInsert START
2024-09-29T07:56:59.693 …ries.ApplicationCosmosAsyncRepositoryV2 DBUG 55cf14750e699f212dfbcaeddf9df77b .070m        7               Executing query to create document 'ABB.EDCS.Persistence.Azure.Storage.Documents.ApplicationGrantDocument'.
2024-09-29T07:56:59.697 Diginsight.Diagnostics.$Activity         DBUG 55cf14750e699f212dfbcaeddf9df77b              8                Operation.CreateItemAsync START
2024-09-29T07:56:59.751 Diginsight.Diagnostics.$Activity         DBUG 55cf14750e699f212dfbcaeddf9df77b .177m   53m  8                Operation.CreateItemAsync END
2024-09-29T07:56:59.757 …ries.ApplicationCosmosAsyncRepositoryV2 DBUG 55cf14750e699f212dfbcaeddf9df77b .100m   65m  7              CosmosDBInsert END
2024-09-29T07:56:59.760 …ries.ApplicationCosmosAsyncRepositoryV2 DBUG 55cf14750e699f212dfbcaeddf9df77b .178m        6             Document created with ID '6122bc4b-1c3e-46a3-8b33-e36eff279206'.
2024-09-29T07:56:59.765 …ries.ApplicationCosmosAsyncRepositoryV2 DBUG 55cf14750e699f212dfbcaeddf9df77b .110m   82m  6            BaseCosmosDBDataRetriever.CreateDocumentAsync END
2024-09-29T07:56:59.770 …ries.ApplicationCosmosAsyncRepositoryV2 DBUG 55cf14750e699f212dfbcaeddf9df77b .075m  168m  5          ApplicationCosmosAsyncRepositoryV2.GrantPermissionOnPlantAsync END
2024-09-29T07:56:59.796 …ries.ApplicationCosmosAsyncRepositoryV2 DBUG 55cf14750e699f212dfbcaeddf9df77b              5          ApplicationCosmosAsyncRepositoryV2.GrantPermissionOnPlantAsync(applicationId:$3f1a01b9-a251-4a37-a40b-00d965b0158c$, plantId:$eed844d6-6565-47fb-91cf-adf28252513f$) START
2024-09-29T07:56:59.807 …ries.ApplicationCosmosAsyncRepositoryV2 DBUG 55cf14750e699f212dfbcaeddf9df77b              6            ApplicationCosmosAsyncRepositoryV2.HasPermissionOnPlantAsync(applicationId:$3f1a01b9-a251-4a37-a40b-00d965b0158c$, plantId:$eed844d6-6565-47fb-91cf-adf28252513f$) START
2024-09-29T07:56:59.810 …ries.ApplicationCosmosAsyncRepositoryV2 DBUG 55cf14750e699f212dfbcaeddf9df77b .065m        6             CosmosDB query for class 'ABB.EDCS.Persistence.Azure.Storage.Documents.ApplicationGrantDocument' in database https://testbiotsdkdocdb.documents.azure.com/, collection 'app'
2024-09-29T07:56:59.813 …ries.ApplicationCosmosAsyncRepositoryV2 TRCE 55cf14750e699f212dfbcaeddf9df77b .331m        6             Query: {"query":"SELECT VALUE root FROM root WHERE ((((root[\"ApplicationId\"] = \"3f1a01b9-a251-4a37-a40b-00d965b0158c\") AND (root[\"Type\"] = \"grant-plant\")) AND ((root[\"Target\"] = \"eed844d6-6565-47fb-91cf-adf28252513f\") OR (root[\"Target\"] = \"00000000-0000-0000-0000-000000000000\"))) AND (root[\"DeletedDateTime\"] = null))"}
2024-09-29T07:56:59.867 …ries.ApplicationCosmosAsyncRepositoryV2 DBUG 55cf14750e699f212dfbcaeddf9df77b .081m   58m  6            ApplicationCosmosAsyncRepositoryV2.HasPermissionOnPlantAsync END
2024-09-29T07:56:59.880 …ries.ApplicationCosmosAsyncRepositoryV2 DBUG 55cf14750e699f212dfbcaeddf9df77b              6            BaseCosmosDBDataRetriever.CreateDocumentAsync(TKey:Guid, TValue:ApplicationGrantDocument, Document:ApplicationGrantDocument{Id:$4a2d13a1-c0ca-4cf5-b8f4-ed1b6a1e1ffb$, Type:"grant-plant", ApplicationId:$3f1a01b9-a251-4a37-a40b-00d965b0158c$, Target:$eed844d6-6565-47fb-91cf-adf28252513f$, UserEmailId:□, Prefix:□, Hash:□, PrimaryKey:□, SecondaryKey:□, SubscriptionStatus:□, SubscriptionScope:□, Creat) START
2024-09-29T07:56:59.887 …ries.ApplicationCosmosAsyncRepositoryV2 DBUG 55cf14750e699f212dfbcaeddf9df77b              7              CosmosDBInsert START
2024-09-29T07:56:59.890 …ries.ApplicationCosmosAsyncRepositoryV2 DBUG 55cf14750e699f212dfbcaeddf9df77b .071m        7               Executing query to create document 'ABB.EDCS.Persistence.Azure.Storage.Documents.ApplicationGrantDocument'.
2024-09-29T07:56:59.894 Diginsight.Diagnostics.$Activity         DBUG 55cf14750e699f212dfbcaeddf9df77b              8                Operation.CreateItemAsync START
2024-09-29T07:56:59.952 Diginsight.Diagnostics.$Activity         DBUG 55cf14750e699f212dfbcaeddf9df77b .075m   57m  8                Operation.CreateItemAsync END
2024-09-29T07:56:59.955 …ries.ApplicationCosmosAsyncRepositoryV2 DBUG 55cf14750e699f212dfbcaeddf9df77b .059m   67m  7              CosmosDBInsert END
2024-09-29T07:56:59.957 …ries.ApplicationCosmosAsyncRepositoryV2 DBUG 55cf14750e699f212dfbcaeddf9df77b .037m        6             Document created with ID '4a2d13a1-c0ca-4cf5-b8f4-ed1b6a1e1ffb'.
2024-09-29T07:56:59.959 …ries.ApplicationCosmosAsyncRepositoryV2 DBUG 55cf14750e699f212dfbcaeddf9df77b .034m   79m  6            BaseCosmosDBDataRetriever.CreateDocumentAsync END
2024-09-29T07:56:59.962 …ries.ApplicationCosmosAsyncRepositoryV2 DBUG 55cf14750e699f212dfbcaeddf9df77b .049m  166m  5          ApplicationCosmosAsyncRepositoryV2.GrantPermissionOnPlantAsync END
2024-09-29T07:56:59.971 …ries.ApplicationCosmosAsyncRepositoryV2 DBUG 55cf14750e699f212dfbcaeddf9df77b              5          ApplicationCosmosAsyncRepositoryV2.GrantPermissionOnPlantAsync(applicationId:$3f1a01b9-a251-4a37-a40b-00d965b0158c$, plantId:$2d4f4b26-7829-4f26-a6ea-c461bb4099fb$) START
2024-09-29T07:56:59.981 …ries.ApplicationCosmosAsyncRepositoryV2 DBUG 55cf14750e699f212dfbcaeddf9df77b              6            ApplicationCosmosAsyncRepositoryV2.HasPermissionOnPlantAsync(applicationId:$3f1a01b9-a251-4a37-a40b-00d965b0158c$, plantId:$2d4f4b26-7829-4f26-a6ea-c461bb4099fb$) START
2024-09-29T07:56:59.982 …ries.ApplicationCosmosAsyncRepositoryV2 DBUG 55cf14750e699f212dfbcaeddf9df77b .058m        6             CosmosDB query for class 'ABB.EDCS.Persistence.Azure.Storage.Documents.ApplicationGrantDocument' in database https://testbiotsdkdocdb.documents.azure.com/, collection 'app'
2024-09-29T07:56:59.984 …ries.ApplicationCosmosAsyncRepositoryV2 TRCE 55cf14750e699f212dfbcaeddf9df77b .080m        6             Query: {"query":"SELECT VALUE root FROM root WHERE ((((root[\"ApplicationId\"] = \"3f1a01b9-a251-4a37-a40b-00d965b0158c\") AND (root[\"Type\"] = \"grant-plant\")) AND ((root[\"Target\"] = \"2d4f4b26-7829-4f26-a6ea-c461bb4099fb\") OR (root[\"Target\"] = \"00000000-0000-0000-0000-000000000000\"))) AND (root[\"DeletedDateTime\"] = null))"}
2024-09-29T07:57:00.034 …ries.ApplicationCosmosAsyncRepositoryV2 DBUG 55cf14750e699f212dfbcaeddf9df77b .068m   53m  6            ApplicationCosmosAsyncRepositoryV2.HasPermissionOnPlantAsync END
2024-09-29T07:57:00.047 …ries.ApplicationCosmosAsyncRepositoryV2 DBUG 55cf14750e699f212dfbcaeddf9df77b              6            BaseCosmosDBDataRetriever.CreateDocumentAsync(TKey:Guid, TValue:ApplicationGrantDocument, Document:ApplicationGrantDocument{Id:$15c7f8c2-1bad-46b6-95a3-bac6165ed1d1$, Type:"grant-plant", ApplicationId:$3f1a01b9-a251-4a37-a40b-00d965b0158c$, Target:$2d4f4b26-7829-4f26-a6ea-c461bb4099fb$, UserEmailId:□, Prefix:□, Hash:□, PrimaryKey:□, SecondaryKey:□, SubscriptionStatus:□, SubscriptionScope:□, Creat) START
2024-09-29T07:57:00.056 …ries.ApplicationCosmosAsyncRepositoryV2 DBUG 55cf14750e699f212dfbcaeddf9df77b              7              CosmosDBInsert START
2024-09-29T07:57:00.058 …ries.ApplicationCosmosAsyncRepositoryV2 DBUG 55cf14750e699f212dfbcaeddf9df77b .046m        7               Executing query to create document 'ABB.EDCS.Persistence.Azure.Storage.Documents.ApplicationGrantDocument'.
2024-09-29T07:57:00.062 Diginsight.Diagnostics.$Activity         DBUG 55cf14750e699f212dfbcaeddf9df77b              8                Operation.CreateItemAsync START
2024-09-29T07:57:00.129 Diginsight.Diagnostics.$Activity         DBUG 55cf14750e699f212dfbcaeddf9df77b .828m   59m  8                Operation.CreateItemAsync END
2024-09-29T07:57:00.135 …ries.ApplicationCosmosAsyncRepositoryV2 DBUG 55cf14750e699f212dfbcaeddf9df77b .864m   78m  7              CosmosDBInsert END
2024-09-29T07:57:00.140 …ries.ApplicationCosmosAsyncRepositoryV2 DBUG 55cf14750e699f212dfbcaeddf9df77b    2m        6             Document created with ID '15c7f8c2-1bad-46b6-95a3-bac6165ed1d1'.
2024-09-29T07:57:00.145 …ries.ApplicationCosmosAsyncRepositoryV2 DBUG 55cf14750e699f212dfbcaeddf9df77b    1m   96m  6            BaseCosmosDBDataRetriever.CreateDocumentAsync END
2024-09-29T07:57:00.151 …ries.ApplicationCosmosAsyncRepositoryV2 DBUG 55cf14750e699f212dfbcaeddf9df77b .087m  179m  5          ApplicationCosmosAsyncRepositoryV2.GrantPermissionOnPlantAsync END
2024-09-29T07:57:00.164 …ries.ApplicationCosmosAsyncRepositoryV2 DBUG 55cf14750e699f212dfbcaeddf9df77b              5          ApplicationCosmosAsyncRepositoryV2.GrantPermissionOnPlantAsync(applicationId:$3f1a01b9-a251-4a37-a40b-00d965b0158c$, plantId:$aea13251-d359-4d22-9d04-ce51fe631780$) START
2024-09-29T07:57:00.177 …ries.ApplicationCosmosAsyncRepositoryV2 DBUG 55cf14750e699f212dfbcaeddf9df77b              6            ApplicationCosmosAsyncRepositoryV2.HasPermissionOnPlantAsync(applicationId:$3f1a01b9-a251-4a37-a40b-00d965b0158c$, plantId:$aea13251-d359-4d22-9d04-ce51fe631780$) START
2024-09-29T07:57:00.179 …ries.ApplicationCosmosAsyncRepositoryV2 DBUG 55cf14750e699f212dfbcaeddf9df77b .060m        6             CosmosDB query for class 'ABB.EDCS.Persistence.Azure.Storage.Documents.ApplicationGrantDocument' in database https://testbiotsdkdocdb.documents.azure.com/, collection 'app'
2024-09-29T07:57:00.182 …ries.ApplicationCosmosAsyncRepositoryV2 TRCE 55cf14750e699f212dfbcaeddf9df77b .069m        6             Query: {"query":"SELECT VALUE root FROM root WHERE ((((root[\"ApplicationId\"] = \"3f1a01b9-a251-4a37-a40b-00d965b0158c\") AND (root[\"Type\"] = \"grant-plant\")) AND ((root[\"Target\"] = \"aea13251-d359-4d22-9d04-ce51fe631780\") OR (root[\"Target\"] = \"00000000-0000-0000-0000-000000000000\"))) AND (root[\"DeletedDateTime\"] = null))"}
2024-09-29T07:57:00.234 …ries.ApplicationCosmosAsyncRepositoryV2 DBUG 55cf14750e699f212dfbcaeddf9df77b .072m   56m  6            ApplicationCosmosAsyncRepositoryV2.HasPermissionOnPlantAsync END
2024-09-29T07:57:00.249 …ries.ApplicationCosmosAsyncRepositoryV2 DBUG 55cf14750e699f212dfbcaeddf9df77b              6            BaseCosmosDBDataRetriever.CreateDocumentAsync(TKey:Guid, TValue:ApplicationGrantDocument, Document:ApplicationGrantDocument{Id:$42898496-fdc2-4aea-b612-f653dfbd9eeb$, Type:"grant-plant", ApplicationId:$3f1a01b9-a251-4a37-a40b-00d965b0158c$, Target:$aea13251-d359-4d22-9d04-ce51fe631780$, UserEmailId:□, Prefix:□, Hash:□, PrimaryKey:□, SecondaryKey:□, SubscriptionStatus:□, SubscriptionScope:□, Creat) START
2024-09-29T07:57:00.257 …ries.ApplicationCosmosAsyncRepositoryV2 DBUG 55cf14750e699f212dfbcaeddf9df77b              7              CosmosDBInsert START
2024-09-29T07:57:00.270 …ries.ApplicationCosmosAsyncRepositoryV2 DBUG 55cf14750e699f212dfbcaeddf9df77b .077m        7               Executing query to create document 'ABB.EDCS.Persistence.Azure.Storage.Documents.ApplicationGrantDocument'.
2024-09-29T07:57:00.273 Diginsight.Diagnostics.$Activity         DBUG 55cf14750e699f212dfbcaeddf9df77b              8                Operation.CreateItemAsync START
2024-09-29T07:57:00.329 Diginsight.Diagnostics.$Activity         DBUG 55cf14750e699f212dfbcaeddf9df77b .075m   56m  8                Operation.CreateItemAsync END
2024-09-29T07:57:00.332 …ries.ApplicationCosmosAsyncRepositoryV2 DBUG 55cf14750e699f212dfbcaeddf9df77b .046m   75m  7              CosmosDBInsert END
2024-09-29T07:57:00.333 …ries.ApplicationCosmosAsyncRepositoryV2 DBUG 55cf14750e699f212dfbcaeddf9df77b .042m        6             Document created with ID '42898496-fdc2-4aea-b612-f653dfbd9eeb'.
2024-09-29T07:57:00.336 …ries.ApplicationCosmosAsyncRepositoryV2 DBUG 55cf14750e699f212dfbcaeddf9df77b .045m   86m  6            BaseCosmosDBDataRetriever.CreateDocumentAsync END
2024-09-29T07:57:00.338 …ries.ApplicationCosmosAsyncRepositoryV2 DBUG 55cf14750e699f212dfbcaeddf9df77b .042m  174m  5          ApplicationCosmosAsyncRepositoryV2.GrantPermissionOnPlantAsync END
2024-09-29T07:57:00.348 …ries.ApplicationCosmosAsyncRepositoryV2 DBUG 55cf14750e699f212dfbcaeddf9df77b              5          ApplicationCosmosAsyncRepositoryV2.GrantPermissionOnPlantAsync(applicationId:$3f1a01b9-a251-4a37-a40b-00d965b0158c$, plantId:$3a852f92-fe84-4323-bd76-51bfb449c3a6$) START
2024-09-29T07:57:00.359 …ries.ApplicationCosmosAsyncRepositoryV2 DBUG 55cf14750e699f212dfbcaeddf9df77b              6            ApplicationCosmosAsyncRepositoryV2.HasPermissionOnPlantAsync(applicationId:$3f1a01b9-a251-4a37-a40b-00d965b0158c$, plantId:$3a852f92-fe84-4323-bd76-51bfb449c3a6$) START
2024-09-29T07:57:00.361 …ries.ApplicationCosmosAsyncRepositoryV2 DBUG 55cf14750e699f212dfbcaeddf9df77b .061m        6             CosmosDB query for class 'ABB.EDCS.Persistence.Azure.Storage.Documents.ApplicationGrantDocument' in database https://testbiotsdkdocdb.documents.azure.com/, collection 'app'
2024-09-29T07:57:00.363 …ries.ApplicationCosmosAsyncRepositoryV2 TRCE 55cf14750e699f212dfbcaeddf9df77b .051m        6             Query: {"query":"SELECT VALUE root FROM root WHERE ((((root[\"ApplicationId\"] = \"3f1a01b9-a251-4a37-a40b-00d965b0158c\") AND (root[\"Type\"] = \"grant-plant\")) AND ((root[\"Target\"] = \"3a852f92-fe84-4323-bd76-51bfb449c3a6\") OR (root[\"Target\"] = \"00000000-0000-0000-0000-000000000000\"))) AND (root[\"DeletedDateTime\"] = null))"}
2024-09-29T07:57:00.412 …ries.ApplicationCosmosAsyncRepositoryV2 DBUG 55cf14750e699f212dfbcaeddf9df77b .067m   52m  6            ApplicationCosmosAsyncRepositoryV2.HasPermissionOnPlantAsync END
2024-09-29T07:57:00.424 …ries.ApplicationCosmosAsyncRepositoryV2 DBUG 55cf14750e699f212dfbcaeddf9df77b              6            BaseCosmosDBDataRetriever.CreateDocumentAsync(TKey:Guid, TValue:ApplicationGrantDocument, Document:ApplicationGrantDocument{Id:$f226bd07-4a8b-4737-a28b-1c49b74ece93$, Type:"grant-plant", ApplicationId:$3f1a01b9-a251-4a37-a40b-00d965b0158c$, Target:$3a852f92-fe84-4323-bd76-51bfb449c3a6$, UserEmailId:□, Prefix:□, Hash:□, PrimaryKey:□, SecondaryKey:□, SubscriptionStatus:□, SubscriptionScope:□, Creat) START
2024-09-29T07:57:00.432 …ries.ApplicationCosmosAsyncRepositoryV2 DBUG 55cf14750e699f212dfbcaeddf9df77b              7              CosmosDBInsert START
2024-09-29T07:57:00.435 …ries.ApplicationCosmosAsyncRepositoryV2 DBUG 55cf14750e699f212dfbcaeddf9df77b .072m        7               Executing query to create document 'ABB.EDCS.Persistence.Azure.Storage.Documents.ApplicationGrantDocument'.
2024-09-29T07:57:00.439 Diginsight.Diagnostics.$Activity         DBUG 55cf14750e699f212dfbcaeddf9df77b              8                Operation.CreateItemAsync START
2024-09-29T07:57:00.500 Diginsight.Diagnostics.$Activity         DBUG 55cf14750e699f212dfbcaeddf9df77b .074m   60m  8                Operation.CreateItemAsync END
2024-09-29T07:57:00.504 …ries.ApplicationCosmosAsyncRepositoryV2 DBUG 55cf14750e699f212dfbcaeddf9df77b .075m   71m  7              CosmosDBInsert END
2024-09-29T07:57:00.520 …ries.ApplicationCosmosAsyncRepositoryV2 DBUG 55cf14750e699f212dfbcaeddf9df77b .590m        6             Document created with ID 'f226bd07-4a8b-4737-a28b-1c49b74ece93'.
2024-09-29T07:57:00.526 …ries.ApplicationCosmosAsyncRepositoryV2 DBUG 55cf14750e699f212dfbcaeddf9df77b .114m  101m  6            BaseCosmosDBDataRetriever.CreateDocumentAsync END
2024-09-29T07:57:00.529 …ries.ApplicationCosmosAsyncRepositoryV2 DBUG 55cf14750e699f212dfbcaeddf9df77b .048m  181m  5          ApplicationCosmosAsyncRepositoryV2.GrantPermissionOnPlantAsync END
2024-09-29T07:57:00.539 …ries.ApplicationCosmosAsyncRepositoryV2 DBUG 55cf14750e699f212dfbcaeddf9df77b              5          ApplicationCosmosAsyncRepositoryV2.GrantPermissionOnPlantAsync(applicationId:$3f1a01b9-a251-4a37-a40b-00d965b0158c$, plantId:$4751f181-05c9-46dd-b748-a890e853500a$) START
2024-09-29T07:57:00.550 …ries.ApplicationCosmosAsyncRepositoryV2 DBUG 55cf14750e699f212dfbcaeddf9df77b              6            ApplicationCosmosAsyncRepositoryV2.HasPermissionOnPlantAsync(applicationId:$3f1a01b9-a251-4a37-a40b-00d965b0158c$, plantId:$4751f181-05c9-46dd-b748-a890e853500a$) START
2024-09-29T07:57:00.552 …ries.ApplicationCosmosAsyncRepositoryV2 DBUG 55cf14750e699f212dfbcaeddf9df77b .058m        6             CosmosDB query for class 'ABB.EDCS.Persistence.Azure.Storage.Documents.ApplicationGrantDocument' in database https://testbiotsdkdocdb.documents.azure.com/, collection 'app'
2024-09-29T07:57:00.554 …ries.ApplicationCosmosAsyncRepositoryV2 TRCE 55cf14750e699f212dfbcaeddf9df77b .058m        6             Query: {"query":"SELECT VALUE root FROM root WHERE ((((root[\"ApplicationId\"] = \"3f1a01b9-a251-4a37-a40b-00d965b0158c\") AND (root[\"Type\"] = \"grant-plant\")) AND ((root[\"Target\"] = \"4751f181-05c9-46dd-b748-a890e853500a\") OR (root[\"Target\"] = \"00000000-0000-0000-0000-000000000000\"))) AND (root[\"DeletedDateTime\"] = null))"}
2024-09-29T07:57:00.614 …ries.ApplicationCosmosAsyncRepositoryV2 DBUG 55cf14750e699f212dfbcaeddf9df77b .094m   63m  6            ApplicationCosmosAsyncRepositoryV2.HasPermissionOnPlantAsync END
2024-09-29T07:57:00.629 …ries.ApplicationCosmosAsyncRepositoryV2 DBUG 55cf14750e699f212dfbcaeddf9df77b              6            BaseCosmosDBDataRetriever.CreateDocumentAsync(TKey:Guid, TValue:ApplicationGrantDocument, Document:ApplicationGrantDocument{Id:$763f6e94-4e31-4dfd-a636-3d0f23dfc2a2$, Type:"grant-plant", ApplicationId:$3f1a01b9-a251-4a37-a40b-00d965b0158c$, Target:$4751f181-05c9-46dd-b748-a890e853500a$, UserEmailId:□, Prefix:□, Hash:□, PrimaryKey:□, SecondaryKey:□, SubscriptionStatus:□, SubscriptionScope:□, Creat) START
2024-09-29T07:57:00.637 …ries.ApplicationCosmosAsyncRepositoryV2 DBUG 55cf14750e699f212dfbcaeddf9df77b              7              CosmosDBInsert START
2024-09-29T07:57:00.640 …ries.ApplicationCosmosAsyncRepositoryV2 DBUG 55cf14750e699f212dfbcaeddf9df77b .060m        7               Executing query to create document 'ABB.EDCS.Persistence.Azure.Storage.Documents.ApplicationGrantDocument'.
2024-09-29T07:57:00.643 Diginsight.Diagnostics.$Activity         DBUG 55cf14750e699f212dfbcaeddf9df77b              8                Operation.CreateItemAsync START
2024-09-29T07:57:00.697 Diginsight.Diagnostics.$Activity         DBUG 55cf14750e699f212dfbcaeddf9df77b .066m   53m  8                Operation.CreateItemAsync END
2024-09-29T07:57:00.701 …ries.ApplicationCosmosAsyncRepositoryV2 DBUG 55cf14750e699f212dfbcaeddf9df77b .058m   62m  7              CosmosDBInsert END
2024-09-29T07:57:00.703 …ries.ApplicationCosmosAsyncRepositoryV2 DBUG 55cf14750e699f212dfbcaeddf9df77b .041m        6             Document created with ID '763f6e94-4e31-4dfd-a636-3d0f23dfc2a2'.
2024-09-29T07:57:00.706 …ries.ApplicationCosmosAsyncRepositoryV2 DBUG 55cf14750e699f212dfbcaeddf9df77b .046m   76m  6            BaseCosmosDBDataRetriever.CreateDocumentAsync END
2024-09-29T07:57:00.709 …ries.ApplicationCosmosAsyncRepositoryV2 DBUG 55cf14750e699f212dfbcaeddf9df77b .055m  169m  5          ApplicationCosmosAsyncRepositoryV2.GrantPermissionOnPlantAsync END
2024-09-29T07:57:00.718 …ries.ApplicationCosmosAsyncRepositoryV2 DBUG 55cf14750e699f212dfbcaeddf9df77b              5          ApplicationCosmosAsyncRepositoryV2.GrantPermissionOnPlantAsync(applicationId:$3f1a01b9-a251-4a37-a40b-00d965b0158c$, plantId:$94ab868f-bec8-4f9e-9bc2-aab7188ca9bc$) START
2024-09-29T07:57:00.733 …ries.ApplicationCosmosAsyncRepositoryV2 DBUG 55cf14750e699f212dfbcaeddf9df77b              6            ApplicationCosmosAsyncRepositoryV2.HasPermissionOnPlantAsync(applicationId:$3f1a01b9-a251-4a37-a40b-00d965b0158c$, plantId:$94ab868f-bec8-4f9e-9bc2-aab7188ca9bc$) START
2024-09-29T07:57:00.735 …ries.ApplicationCosmosAsyncRepositoryV2 DBUG 55cf14750e699f212dfbcaeddf9df77b .106m        6             CosmosDB query for class 'ABB.EDCS.Persistence.Azure.Storage.Documents.ApplicationGrantDocument' in database https://testbiotsdkdocdb.documents.azure.com/, collection 'app'
2024-09-29T07:57:00.738 …ries.ApplicationCosmosAsyncRepositoryV2 TRCE 55cf14750e699f212dfbcaeddf9df77b .051m        6             Query: {"query":"SELECT VALUE root FROM root WHERE ((((root[\"ApplicationId\"] = \"3f1a01b9-a251-4a37-a40b-00d965b0158c\") AND (root[\"Type\"] = \"grant-plant\")) AND ((root[\"Target\"] = \"94ab868f-bec8-4f9e-9bc2-aab7188ca9bc\") OR (root[\"Target\"] = \"00000000-0000-0000-0000-000000000000\"))) AND (root[\"DeletedDateTime\"] = null))"}
2024-09-29T07:57:00.789 …ries.ApplicationCosmosAsyncRepositoryV2 DBUG 55cf14750e699f212dfbcaeddf9df77b .067m   57m  6            ApplicationCosmosAsyncRepositoryV2.HasPermissionOnPlantAsync END
2024-09-29T07:57:00.804 …ries.ApplicationCosmosAsyncRepositoryV2 DBUG 55cf14750e699f212dfbcaeddf9df77b              6            BaseCosmosDBDataRetriever.CreateDocumentAsync(TKey:Guid, TValue:ApplicationGrantDocument, Document:ApplicationGrantDocument{Id:$1c05602b-025c-4d70-bcaa-b6dcbeda6874$, Type:"grant-plant", ApplicationId:$3f1a01b9-a251-4a37-a40b-00d965b0158c$, Target:$94ab868f-bec8-4f9e-9bc2-aab7188ca9bc$, UserEmailId:□, Prefix:□, Hash:□, PrimaryKey:□, SecondaryKey:□, SubscriptionStatus:□, SubscriptionScope:□, Creat) START
2024-09-29T07:57:00.814 …ries.ApplicationCosmosAsyncRepositoryV2 DBUG 55cf14750e699f212dfbcaeddf9df77b              7              CosmosDBInsert START
2024-09-29T07:57:00.816 …ries.ApplicationCosmosAsyncRepositoryV2 DBUG 55cf14750e699f212dfbcaeddf9df77b .047m        7               Executing query to create document 'ABB.EDCS.Persistence.Azure.Storage.Documents.ApplicationGrantDocument'.
2024-09-29T07:57:00.819 Diginsight.Diagnostics.$Activity         DBUG 55cf14750e699f212dfbcaeddf9df77b              8                Operation.CreateItemAsync START
2024-09-29T07:57:00.878 Diginsight.Diagnostics.$Activity         DBUG 55cf14750e699f212dfbcaeddf9df77b .066m   58m  8                Operation.CreateItemAsync END
2024-09-29T07:57:00.881 …ries.ApplicationCosmosAsyncRepositoryV2 DBUG 55cf14750e699f212dfbcaeddf9df77b .044m   67m  7              CosmosDBInsert END
2024-09-29T07:57:00.882 …ries.ApplicationCosmosAsyncRepositoryV2 DBUG 55cf14750e699f212dfbcaeddf9df77b .046m        6             Document created with ID '1c05602b-025c-4d70-bcaa-b6dcbeda6874'.
2024-09-29T07:57:00.885 …ries.ApplicationCosmosAsyncRepositoryV2 DBUG 55cf14750e699f212dfbcaeddf9df77b .045m   80m  6            BaseCosmosDBDataRetriever.CreateDocumentAsync END
2024-09-29T07:57:00.888 …ries.ApplicationCosmosAsyncRepositoryV2 DBUG 55cf14750e699f212dfbcaeddf9df77b .055m  169m  5          ApplicationCosmosAsyncRepositoryV2.GrantPermissionOnPlantAsync END
2024-09-29T07:57:00.899 …ries.ApplicationCosmosAsyncRepositoryV2 DBUG 55cf14750e699f212dfbcaeddf9df77b              5          ApplicationCosmosAsyncRepositoryV2.GrantPermissionOnPlantAsync(applicationId:$3f1a01b9-a251-4a37-a40b-00d965b0158c$, plantId:$202f30f1-937d-4fae-b96a-0455f96c42eb$) START
2024-09-29T07:57:00.907 …ries.ApplicationCosmosAsyncRepositoryV2 DBUG 55cf14750e699f212dfbcaeddf9df77b              6            ApplicationCosmosAsyncRepositoryV2.HasPermissionOnPlantAsync(applicationId:$3f1a01b9-a251-4a37-a40b-00d965b0158c$, plantId:$202f30f1-937d-4fae-b96a-0455f96c42eb$) START
2024-09-29T07:57:00.909 …ries.ApplicationCosmosAsyncRepositoryV2 DBUG 55cf14750e699f212dfbcaeddf9df77b .051m        6             CosmosDB query for class 'ABB.EDCS.Persistence.Azure.Storage.Documents.ApplicationGrantDocument' in database https://testbiotsdkdocdb.documents.azure.com/, collection 'app'
2024-09-29T07:57:00.911 …ries.ApplicationCosmosAsyncRepositoryV2 TRCE 55cf14750e699f212dfbcaeddf9df77b .044m        6             Query: {"query":"SELECT VALUE root FROM root WHERE ((((root[\"ApplicationId\"] = \"3f1a01b9-a251-4a37-a40b-00d965b0158c\") AND (root[\"Type\"] = \"grant-plant\")) AND ((root[\"Target\"] = \"202f30f1-937d-4fae-b96a-0455f96c42eb\") OR (root[\"Target\"] = \"00000000-0000-0000-0000-000000000000\"))) AND (root[\"DeletedDateTime\"] = null))"}
2024-09-29T07:57:00.959 …ries.ApplicationCosmosAsyncRepositoryV2 DBUG 55cf14750e699f212dfbcaeddf9df77b .076m   52m  6            ApplicationCosmosAsyncRepositoryV2.HasPermissionOnPlantAsync END
2024-09-29T07:57:00.972 …ries.ApplicationCosmosAsyncRepositoryV2 DBUG 55cf14750e699f212dfbcaeddf9df77b              6            BaseCosmosDBDataRetriever.CreateDocumentAsync(TKey:Guid, TValue:ApplicationGrantDocument, Document:ApplicationGrantDocument{Id:$3d7ac2a7-4144-4b35-911b-4a378abbbf8f$, Type:"grant-plant", ApplicationId:$3f1a01b9-a251-4a37-a40b-00d965b0158c$, Target:$202f30f1-937d-4fae-b96a-0455f96c42eb$, UserEmailId:□, Prefix:□, Hash:□, PrimaryKey:□, SecondaryKey:□, SubscriptionStatus:□, SubscriptionScope:□, Creat) START
2024-09-29T07:57:00.979 …ries.ApplicationCosmosAsyncRepositoryV2 DBUG 55cf14750e699f212dfbcaeddf9df77b              7              CosmosDBInsert START
2024-09-29T07:57:00.981 …ries.ApplicationCosmosAsyncRepositoryV2 DBUG 55cf14750e699f212dfbcaeddf9df77b .055m        7               Executing query to create document 'ABB.EDCS.Persistence.Azure.Storage.Documents.ApplicationGrantDocument'.
2024-09-29T07:57:00.984 Diginsight.Diagnostics.$Activity         DBUG 55cf14750e699f212dfbcaeddf9df77b              8                Operation.CreateItemAsync START
2024-09-29T07:57:01.036 Diginsight.Diagnostics.$Activity         DBUG 55cf14750e699f212dfbcaeddf9df77b .064m   51m  8                Operation.CreateItemAsync END
2024-09-29T07:57:01.038 …ries.ApplicationCosmosAsyncRepositoryV2 DBUG 55cf14750e699f212dfbcaeddf9df77b .060m   59m  7              CosmosDBInsert END
2024-09-29T07:57:01.040 …ries.ApplicationCosmosAsyncRepositoryV2 DBUG 55cf14750e699f212dfbcaeddf9df77b .049m        6             Document created with ID '3d7ac2a7-4144-4b35-911b-4a378abbbf8f'.
2024-09-29T07:57:01.043 …ries.ApplicationCosmosAsyncRepositoryV2 DBUG 55cf14750e699f212dfbcaeddf9df77b .047m   70m  6            BaseCosmosDBDataRetriever.CreateDocumentAsync END
2024-09-29T07:57:01.046 …ries.ApplicationCosmosAsyncRepositoryV2 DBUG 55cf14750e699f212dfbcaeddf9df77b .056m  147m  5          ApplicationCosmosAsyncRepositoryV2.GrantPermissionOnPlantAsync END
2024-09-29T07:57:01.056 …ries.ApplicationCosmosAsyncRepositoryV2 DBUG 55cf14750e699f212dfbcaeddf9df77b              5          ApplicationCosmosAsyncRepositoryV2.GrantPermissionOnPlantAsync(applicationId:$3f1a01b9-a251-4a37-a40b-00d965b0158c$, plantId:$8a5abe3a-b4f7-492f-a015-2df9e64fa098$) START
2024-09-29T07:57:01.065 …ries.ApplicationCosmosAsyncRepositoryV2 DBUG 55cf14750e699f212dfbcaeddf9df77b              6            ApplicationCosmosAsyncRepositoryV2.HasPermissionOnPlantAsync(applicationId:$3f1a01b9-a251-4a37-a40b-00d965b0158c$, plantId:$8a5abe3a-b4f7-492f-a015-2df9e64fa098$) START
2024-09-29T07:57:01.067 …ries.ApplicationCosmosAsyncRepositoryV2 DBUG 55cf14750e699f212dfbcaeddf9df77b .069m        6             CosmosDB query for class 'ABB.EDCS.Persistence.Azure.Storage.Documents.ApplicationGrantDocument' in database https://testbiotsdkdocdb.documents.azure.com/, collection 'app'
2024-09-29T07:57:01.069 …ries.ApplicationCosmosAsyncRepositoryV2 TRCE 55cf14750e699f212dfbcaeddf9df77b .049m        6             Query: {"query":"SELECT VALUE root FROM root WHERE ((((root[\"ApplicationId\"] = \"3f1a01b9-a251-4a37-a40b-00d965b0158c\") AND (root[\"Type\"] = \"grant-plant\")) AND ((root[\"Target\"] = \"8a5abe3a-b4f7-492f-a015-2df9e64fa098\") OR (root[\"Target\"] = \"00000000-0000-0000-0000-000000000000\"))) AND (root[\"DeletedDateTime\"] = null))"}
2024-09-29T07:57:01.126 …ries.ApplicationCosmosAsyncRepositoryV2 DBUG 55cf14750e699f212dfbcaeddf9df77b .077m   60m  6            ApplicationCosmosAsyncRepositoryV2.HasPermissionOnPlantAsync END
2024-09-29T07:57:01.142 …ries.ApplicationCosmosAsyncRepositoryV2 DBUG 55cf14750e699f212dfbcaeddf9df77b              6            BaseCosmosDBDataRetriever.CreateDocumentAsync(TKey:Guid, TValue:ApplicationGrantDocument, Document:ApplicationGrantDocument{Id:$f977dc27-9434-4aff-bb06-f603dea39a54$, Type:"grant-plant", ApplicationId:$3f1a01b9-a251-4a37-a40b-00d965b0158c$, Target:$8a5abe3a-b4f7-492f-a015-2df9e64fa098$, UserEmailId:□, Prefix:□, Hash:□, PrimaryKey:□, SecondaryKey:□, SubscriptionStatus:□, SubscriptionScope:□, Creat) START
2024-09-29T07:57:01.152 …ries.ApplicationCosmosAsyncRepositoryV2 DBUG 55cf14750e699f212dfbcaeddf9df77b              7              CosmosDBInsert START
2024-09-29T07:57:01.155 …ries.ApplicationCosmosAsyncRepositoryV2 DBUG 55cf14750e699f212dfbcaeddf9df77b .175m        7               Executing query to create document 'ABB.EDCS.Persistence.Azure.Storage.Documents.ApplicationGrantDocument'.
2024-09-29T07:57:01.159 Diginsight.Diagnostics.$Activity         DBUG 55cf14750e699f212dfbcaeddf9df77b              8                Operation.CreateItemAsync START
2024-09-29T07:57:01.213 Diginsight.Diagnostics.$Activity         DBUG 55cf14750e699f212dfbcaeddf9df77b .067m   54m  8                Operation.CreateItemAsync END
2024-09-29T07:57:01.216 …ries.ApplicationCosmosAsyncRepositoryV2 DBUG 55cf14750e699f212dfbcaeddf9df77b .039m   64m  7              CosmosDBInsert END
2024-09-29T07:57:01.217 …ries.ApplicationCosmosAsyncRepositoryV2 DBUG 55cf14750e699f212dfbcaeddf9df77b .047m        6             Document created with ID 'f977dc27-9434-4aff-bb06-f603dea39a54'.
2024-09-29T07:57:01.220 …ries.ApplicationCosmosAsyncRepositoryV2 DBUG 55cf14750e699f212dfbcaeddf9df77b .045m   78m  6            BaseCosmosDBDataRetriever.CreateDocumentAsync END
2024-09-29T07:57:01.223 …ries.ApplicationCosmosAsyncRepositoryV2 DBUG 55cf14750e699f212dfbcaeddf9df77b .051m  166m  5          ApplicationCosmosAsyncRepositoryV2.GrantPermissionOnPlantAsync END
2024-09-29T07:57:01.231 …ries.ApplicationCosmosAsyncRepositoryV2 DBUG 55cf14750e699f212dfbcaeddf9df77b              5          ApplicationCosmosAsyncRepositoryV2.GrantPermissionOnPlantAsync(applicationId:$3f1a01b9-a251-4a37-a40b-00d965b0158c$, plantId:$fb3898ef-eb24-49ec-88d2-325b7dd5c83b$) START
2024-09-29T07:57:01.239 …ries.ApplicationCosmosAsyncRepositoryV2 DBUG 55cf14750e699f212dfbcaeddf9df77b              6            ApplicationCosmosAsyncRepositoryV2.HasPermissionOnPlantAsync(applicationId:$3f1a01b9-a251-4a37-a40b-00d965b0158c$, plantId:$fb3898ef-eb24-49ec-88d2-325b7dd5c83b$) START
2024-09-29T07:57:01.241 …ries.ApplicationCosmosAsyncRepositoryV2 DBUG 55cf14750e699f212dfbcaeddf9df77b .041m        6             CosmosDB query for class 'ABB.EDCS.Persistence.Azure.Storage.Documents.ApplicationGrantDocument' in database https://testbiotsdkdocdb.documents.azure.com/, collection 'app'
2024-09-29T07:57:01.243 …ries.ApplicationCosmosAsyncRepositoryV2 TRCE 55cf14750e699f212dfbcaeddf9df77b .047m        6             Query: {"query":"SELECT VALUE root FROM root WHERE ((((root[\"ApplicationId\"] = \"3f1a01b9-a251-4a37-a40b-00d965b0158c\") AND (root[\"Type\"] = \"grant-plant\")) AND ((root[\"Target\"] = \"fb3898ef-eb24-49ec-88d2-325b7dd5c83b\") OR (root[\"Target\"] = \"00000000-0000-0000-0000-000000000000\"))) AND (root[\"DeletedDateTime\"] = null))"}
2024-09-29T07:57:01.296 …ries.ApplicationCosmosAsyncRepositoryV2 DBUG 55cf14750e699f212dfbcaeddf9df77b .064m   57m  6            ApplicationCosmosAsyncRepositoryV2.HasPermissionOnPlantAsync END
2024-09-29T07:57:01.308 …ries.ApplicationCosmosAsyncRepositoryV2 DBUG 55cf14750e699f212dfbcaeddf9df77b              6            BaseCosmosDBDataRetriever.CreateDocumentAsync(TKey:Guid, TValue:ApplicationGrantDocument, Document:ApplicationGrantDocument{Id:$c193a046-ef95-4a68-92d2-d9683f0eb776$, Type:"grant-plant", ApplicationId:$3f1a01b9-a251-4a37-a40b-00d965b0158c$, Target:$fb3898ef-eb24-49ec-88d2-325b7dd5c83b$, UserEmailId:□, Prefix:□, Hash:□, PrimaryKey:□, SecondaryKey:□, SubscriptionStatus:□, SubscriptionScope:□, Creat) START
2024-09-29T07:57:01.315 …ries.ApplicationCosmosAsyncRepositoryV2 DBUG 55cf14750e699f212dfbcaeddf9df77b              7              CosmosDBInsert START
2024-09-29T07:57:01.317 …ries.ApplicationCosmosAsyncRepositoryV2 DBUG 55cf14750e699f212dfbcaeddf9df77b .041m        7               Executing query to create document 'ABB.EDCS.Persistence.Azure.Storage.Documents.ApplicationGrantDocument'.
2024-09-29T07:57:01.320 Diginsight.Diagnostics.$Activity         DBUG 55cf14750e699f212dfbcaeddf9df77b              8                Operation.CreateItemAsync START
2024-09-29T07:57:01.370 Diginsight.Diagnostics.$Activity         DBUG 55cf14750e699f212dfbcaeddf9df77b .067m   50m  8                Operation.CreateItemAsync END
2024-09-29T07:57:01.374 …ries.ApplicationCosmosAsyncRepositoryV2 DBUG 55cf14750e699f212dfbcaeddf9df77b .064m   58m  7              CosmosDBInsert END
2024-09-29T07:57:01.376 …ries.ApplicationCosmosAsyncRepositoryV2 DBUG 55cf14750e699f212dfbcaeddf9df77b .057m        6             Document created with ID 'c193a046-ef95-4a68-92d2-d9683f0eb776'.
2024-09-29T07:57:01.379 …ries.ApplicationCosmosAsyncRepositoryV2 DBUG 55cf14750e699f212dfbcaeddf9df77b .050m   70m  6            BaseCosmosDBDataRetriever.CreateDocumentAsync END
2024-09-29T07:57:01.382 …ries.ApplicationCosmosAsyncRepositoryV2 DBUG 55cf14750e699f212dfbcaeddf9df77b .052m  150m  5          ApplicationCosmosAsyncRepositoryV2.GrantPermissionOnPlantAsync END
2024-09-29T07:57:01.392 …ries.ApplicationCosmosAsyncRepositoryV2 DBUG 55cf14750e699f212dfbcaeddf9df77b              5          ApplicationCosmosAsyncRepositoryV2.GrantPermissionOnPlantAsync(applicationId:$3f1a01b9-a251-4a37-a40b-00d965b0158c$, plantId:$7f4b8a0f-33e5-41b5-83f3-4b9a774d9ea9$) START
2024-09-29T07:57:01.401 …ries.ApplicationCosmosAsyncRepositoryV2 DBUG 55cf14750e699f212dfbcaeddf9df77b              6            ApplicationCosmosAsyncRepositoryV2.HasPermissionOnPlantAsync(applicationId:$3f1a01b9-a251-4a37-a40b-00d965b0158c$, plantId:$7f4b8a0f-33e5-41b5-83f3-4b9a774d9ea9$) START
2024-09-29T07:57:01.403 …ries.ApplicationCosmosAsyncRepositoryV2 DBUG 55cf14750e699f212dfbcaeddf9df77b .047m        6             CosmosDB query for class 'ABB.EDCS.Persistence.Azure.Storage.Documents.ApplicationGrantDocument' in database https://testbiotsdkdocdb.documents.azure.com/, collection 'app'
2024-09-29T07:57:01.405 …ries.ApplicationCosmosAsyncRepositoryV2 TRCE 55cf14750e699f212dfbcaeddf9df77b .114m        6             Query: {"query":"SELECT VALUE root FROM root WHERE ((((root[\"ApplicationId\"] = \"3f1a01b9-a251-4a37-a40b-00d965b0158c\") AND (root[\"Type\"] = \"grant-plant\")) AND ((root[\"Target\"] = \"7f4b8a0f-33e5-41b5-83f3-4b9a774d9ea9\") OR (root[\"Target\"] = \"00000000-0000-0000-0000-000000000000\"))) AND (root[\"DeletedDateTime\"] = null))"}
2024-09-29T07:57:01.465 …ries.ApplicationCosmosAsyncRepositoryV2 DBUG 55cf14750e699f212dfbcaeddf9df77b .070m   63m  6            ApplicationCosmosAsyncRepositoryV2.HasPermissionOnPlantAsync END
2024-09-29T07:57:01.478 …ries.ApplicationCosmosAsyncRepositoryV2 DBUG 55cf14750e699f212dfbcaeddf9df77b              6            BaseCosmosDBDataRetriever.CreateDocumentAsync(TKey:Guid, TValue:ApplicationGrantDocument, Document:ApplicationGrantDocument{Id:$667f8dab-8b9b-48bb-9190-f065f9ac8b3f$, Type:"grant-plant", ApplicationId:$3f1a01b9-a251-4a37-a40b-00d965b0158c$, Target:$7f4b8a0f-33e5-41b5-83f3-4b9a774d9ea9$, UserEmailId:□, Prefix:□, Hash:□, PrimaryKey:□, SecondaryKey:□, SubscriptionStatus:□, SubscriptionScope:□, Creat) START
2024-09-29T07:57:01.485 …ries.ApplicationCosmosAsyncRepositoryV2 DBUG 55cf14750e699f212dfbcaeddf9df77b              7              CosmosDBInsert START
2024-09-29T07:57:01.487 …ries.ApplicationCosmosAsyncRepositoryV2 DBUG 55cf14750e699f212dfbcaeddf9df77b .055m        7               Executing query to create document 'ABB.EDCS.Persistence.Azure.Storage.Documents.ApplicationGrantDocument'.
2024-09-29T07:57:01.490 Diginsight.Diagnostics.$Activity         DBUG 55cf14750e699f212dfbcaeddf9df77b              8                Operation.CreateItemAsync START
2024-09-29T07:57:01.552 Diginsight.Diagnostics.$Activity         DBUG 55cf14750e699f212dfbcaeddf9df77b .759m   60m  8                Operation.CreateItemAsync END
2024-09-29T07:57:01.566 …ries.ApplicationCosmosAsyncRepositoryV2 DBUG 55cf14750e699f212dfbcaeddf9df77b   10m   70m  7              CosmosDBInsert END
2024-09-29T07:57:01.569 …ries.ApplicationCosmosAsyncRepositoryV2 DBUG 55cf14750e699f212dfbcaeddf9df77b .770m        6             Document created with ID '667f8dab-8b9b-48bb-9190-f065f9ac8b3f'.
2024-09-29T07:57:01.573 …ries.ApplicationCosmosAsyncRepositoryV2 DBUG 55cf14750e699f212dfbcaeddf9df77b .088m   94m  6            BaseCosmosDBDataRetriever.CreateDocumentAsync END
2024-09-29T07:57:01.577 …ries.ApplicationCosmosAsyncRepositoryV2 DBUG 55cf14750e699f212dfbcaeddf9df77b .043m  184m  5          ApplicationCosmosAsyncRepositoryV2.GrantPermissionOnPlantAsync END
2024-09-29T07:57:01.597 …ries.ApplicationCosmosAsyncRepositoryV2 DBUG 55cf14750e699f212dfbcaeddf9df77b              5          ApplicationCosmosAsyncRepositoryV2.GrantPermissionOnPlantAsync(applicationId:$3f1a01b9-a251-4a37-a40b-00d965b0158c$, plantId:$1193e62b-8ec7-4594-ab97-74711eeb1591$) START
2024-09-29T07:57:01.606 …ries.ApplicationCosmosAsyncRepositoryV2 DBUG 55cf14750e699f212dfbcaeddf9df77b              6            ApplicationCosmosAsyncRepositoryV2.HasPermissionOnPlantAsync(applicationId:$3f1a01b9-a251-4a37-a40b-00d965b0158c$, plantId:$1193e62b-8ec7-4594-ab97-74711eeb1591$) START
2024-09-29T07:57:01.607 …ries.ApplicationCosmosAsyncRepositoryV2 DBUG 55cf14750e699f212dfbcaeddf9df77b .045m        6             CosmosDB query for class 'ABB.EDCS.Persistence.Azure.Storage.Documents.ApplicationGrantDocument' in database https://testbiotsdkdocdb.documents.azure.com/, collection 'app'
2024-09-29T07:57:01.609 …ries.ApplicationCosmosAsyncRepositoryV2 TRCE 55cf14750e699f212dfbcaeddf9df77b .044m        6             Query: {"query":"SELECT VALUE root FROM root WHERE ((((root[\"ApplicationId\"] = \"3f1a01b9-a251-4a37-a40b-00d965b0158c\") AND (root[\"Type\"] = \"grant-plant\")) AND ((root[\"Target\"] = \"1193e62b-8ec7-4594-ab97-74711eeb1591\") OR (root[\"Target\"] = \"00000000-0000-0000-0000-000000000000\"))) AND (root[\"DeletedDateTime\"] = null))"}
2024-09-29T07:57:01.663 …ries.ApplicationCosmosAsyncRepositoryV2 DBUG 55cf14750e699f212dfbcaeddf9df77b .071m   57m  6            ApplicationCosmosAsyncRepositoryV2.HasPermissionOnPlantAsync END
2024-09-29T07:57:01.675 …ries.ApplicationCosmosAsyncRepositoryV2 DBUG 55cf14750e699f212dfbcaeddf9df77b              6            BaseCosmosDBDataRetriever.CreateDocumentAsync(TKey:Guid, TValue:ApplicationGrantDocument, Document:ApplicationGrantDocument{Id:$507f5727-6812-41b8-97f7-db74fc4bd439$, Type:"grant-plant", ApplicationId:$3f1a01b9-a251-4a37-a40b-00d965b0158c$, Target:$1193e62b-8ec7-4594-ab97-74711eeb1591$, UserEmailId:□, Prefix:□, Hash:□, PrimaryKey:□, SecondaryKey:□, SubscriptionStatus:□, SubscriptionScope:□, Creat) START
2024-09-29T07:57:01.681 …ries.ApplicationCosmosAsyncRepositoryV2 DBUG 55cf14750e699f212dfbcaeddf9df77b              7              CosmosDBInsert START
2024-09-29T07:57:01.683 …ries.ApplicationCosmosAsyncRepositoryV2 DBUG 55cf14750e699f212dfbcaeddf9df77b .036m        7               Executing query to create document 'ABB.EDCS.Persistence.Azure.Storage.Documents.ApplicationGrantDocument'.
2024-09-29T07:57:01.686 Diginsight.Diagnostics.$Activity         DBUG 55cf14750e699f212dfbcaeddf9df77b              8                Operation.CreateItemAsync START
2024-09-29T07:57:01.740 Diginsight.Diagnostics.$Activity         DBUG 55cf14750e699f212dfbcaeddf9df77b .091m   53m  8                Operation.CreateItemAsync END
2024-09-29T07:57:01.758 …ries.ApplicationCosmosAsyncRepositoryV2 DBUG 55cf14750e699f212dfbcaeddf9df77b   14m   61m  7              CosmosDBInsert END
2024-09-29T07:57:01.760 …ries.ApplicationCosmosAsyncRepositoryV2 DBUG 55cf14750e699f212dfbcaeddf9df77b .052m        6             Document created with ID '507f5727-6812-41b8-97f7-db74fc4bd439'.
2024-09-29T07:57:01.763 …ries.ApplicationCosmosAsyncRepositoryV2 DBUG 55cf14750e699f212dfbcaeddf9df77b .331m   87m  6            BaseCosmosDBDataRetriever.CreateDocumentAsync END
2024-09-29T07:57:01.767 …ries.ApplicationCosmosAsyncRepositoryV2 DBUG 55cf14750e699f212dfbcaeddf9df77b .439m  169m  5          ApplicationCosmosAsyncRepositoryV2.GrantPermissionOnPlantAsync END
2024-09-29T07:57:01.778 …ries.ApplicationCosmosAsyncRepositoryV2 DBUG 55cf14750e699f212dfbcaeddf9df77b              5          ApplicationCosmosAsyncRepositoryV2.GrantPermissionOnPlantAsync(applicationId:$3f1a01b9-a251-4a37-a40b-00d965b0158c$, plantId:$89eef48f-0c85-4592-8396-3f3e8656ed03$) START
2024-09-29T07:57:01.789 …ries.ApplicationCosmosAsyncRepositoryV2 DBUG 55cf14750e699f212dfbcaeddf9df77b              6            ApplicationCosmosAsyncRepositoryV2.HasPermissionOnPlantAsync(applicationId:$3f1a01b9-a251-4a37-a40b-00d965b0158c$, plantId:$89eef48f-0c85-4592-8396-3f3e8656ed03$) START
2024-09-29T07:57:01.791 …ries.ApplicationCosmosAsyncRepositoryV2 DBUG 55cf14750e699f212dfbcaeddf9df77b .076m        6             CosmosDB query for class 'ABB.EDCS.Persistence.Azure.Storage.Documents.ApplicationGrantDocument' in database https://testbiotsdkdocdb.documents.azure.com/, collection 'app'
2024-09-29T07:57:01.795 …ries.ApplicationCosmosAsyncRepositoryV2 TRCE 55cf14750e699f212dfbcaeddf9df77b .350m        6             Query: {"query":"SELECT VALUE root FROM root WHERE ((((root[\"ApplicationId\"] = \"3f1a01b9-a251-4a37-a40b-00d965b0158c\") AND (root[\"Type\"] = \"grant-plant\")) AND ((root[\"Target\"] = \"89eef48f-0c85-4592-8396-3f3e8656ed03\") OR (root[\"Target\"] = \"00000000-0000-0000-0000-000000000000\"))) AND (root[\"DeletedDateTime\"] = null))"}
2024-09-29T07:57:01.854 …ries.ApplicationCosmosAsyncRepositoryV2 DBUG 55cf14750e699f212dfbcaeddf9df77b .067m   65m  6            ApplicationCosmosAsyncRepositoryV2.HasPermissionOnPlantAsync END
2024-09-29T07:57:01.865 …ries.ApplicationCosmosAsyncRepositoryV2 DBUG 55cf14750e699f212dfbcaeddf9df77b              6            BaseCosmosDBDataRetriever.CreateDocumentAsync(TKey:Guid, TValue:ApplicationGrantDocument, Document:ApplicationGrantDocument{Id:$e1bc0f3c-fedd-44e5-9a19-8f38973cb6be$, Type:"grant-plant", ApplicationId:$3f1a01b9-a251-4a37-a40b-00d965b0158c$, Target:$89eef48f-0c85-4592-8396-3f3e8656ed03$, UserEmailId:□, Prefix:□, Hash:□, PrimaryKey:□, SecondaryKey:□, SubscriptionStatus:□, SubscriptionScope:□, Creat) START
2024-09-29T07:57:01.871 …ries.ApplicationCosmosAsyncRepositoryV2 DBUG 55cf14750e699f212dfbcaeddf9df77b              7              CosmosDBInsert START
2024-09-29T07:57:01.888 …ries.ApplicationCosmosAsyncRepositoryV2 DBUG 55cf14750e699f212dfbcaeddf9df77b .070m        7               Executing query to create document 'ABB.EDCS.Persistence.Azure.Storage.Documents.ApplicationGrantDocument'.
2024-09-29T07:57:01.892 Diginsight.Diagnostics.$Activity         DBUG 55cf14750e699f212dfbcaeddf9df77b              8                Operation.CreateItemAsync START
2024-09-29T07:57:01.945 Diginsight.Diagnostics.$Activity         DBUG 55cf14750e699f212dfbcaeddf9df77b    2m   51m  8                Operation.CreateItemAsync END
2024-09-29T07:57:01.950 …ries.ApplicationCosmosAsyncRepositoryV2 DBUG 55cf14750e699f212dfbcaeddf9df77b .840m   77m  7              CosmosDBInsert END
2024-09-29T07:57:01.953 …ries.ApplicationCosmosAsyncRepositoryV2 DBUG 55cf14750e699f212dfbcaeddf9df77b .644m        6             Document created with ID 'e1bc0f3c-fedd-44e5-9a19-8f38973cb6be'.
2024-09-29T07:57:01.958 …ries.ApplicationCosmosAsyncRepositoryV2 DBUG 55cf14750e699f212dfbcaeddf9df77b .366m   92m  6            BaseCosmosDBDataRetriever.CreateDocumentAsync END
2024-09-29T07:57:01.961 …ries.ApplicationCosmosAsyncRepositoryV2 DBUG 55cf14750e699f212dfbcaeddf9df77b .067m  183m  5          ApplicationCosmosAsyncRepositoryV2.GrantPermissionOnPlantAsync END
2024-09-29T07:57:01.972 …ries.ApplicationCosmosAsyncRepositoryV2 DBUG 55cf14750e699f212dfbcaeddf9df77b              5          ApplicationCosmosAsyncRepositoryV2.GrantPermissionOnPlantAsync(applicationId:$3f1a01b9-a251-4a37-a40b-00d965b0158c$, plantId:$08584d51-a2ff-4637-914d-f85504c06e5b$) START
2024-09-29T07:57:01.983 …ries.ApplicationCosmosAsyncRepositoryV2 DBUG 55cf14750e699f212dfbcaeddf9df77b              6            ApplicationCosmosAsyncRepositoryV2.HasPermissionOnPlantAsync(applicationId:$3f1a01b9-a251-4a37-a40b-00d965b0158c$, plantId:$08584d51-a2ff-4637-914d-f85504c06e5b$) START
2024-09-29T07:57:01.986 …ries.ApplicationCosmosAsyncRepositoryV2 DBUG 55cf14750e699f212dfbcaeddf9df77b .650m        6             CosmosDB query for class 'ABB.EDCS.Persistence.Azure.Storage.Documents.ApplicationGrantDocument' in database https://testbiotsdkdocdb.documents.azure.com/, collection 'app'
2024-09-29T07:57:01.990 …ries.ApplicationCosmosAsyncRepositoryV2 TRCE 55cf14750e699f212dfbcaeddf9df77b .376m        6             Query: {"query":"SELECT VALUE root FROM root WHERE ((((root[\"ApplicationId\"] = \"3f1a01b9-a251-4a37-a40b-00d965b0158c\") AND (root[\"Type\"] = \"grant-plant\")) AND ((root[\"Target\"] = \"08584d51-a2ff-4637-914d-f85504c06e5b\") OR (root[\"Target\"] = \"00000000-0000-0000-0000-000000000000\"))) AND (root[\"DeletedDateTime\"] = null))"}
2024-09-29T07:57:02.041 …ries.ApplicationCosmosAsyncRepositoryV2 DBUG 55cf14750e699f212dfbcaeddf9df77b .076m   58m  6            ApplicationCosmosAsyncRepositoryV2.HasPermissionOnPlantAsync END
2024-09-29T07:57:02.055 …ries.ApplicationCosmosAsyncRepositoryV2 DBUG 55cf14750e699f212dfbcaeddf9df77b              6            BaseCosmosDBDataRetriever.CreateDocumentAsync(TKey:Guid, TValue:ApplicationGrantDocument, Document:ApplicationGrantDocument{Id:$382ae8dd-a46a-4aeb-8ea2-73f0d2f8a73c$, Type:"grant-plant", ApplicationId:$3f1a01b9-a251-4a37-a40b-00d965b0158c$, Target:$08584d51-a2ff-4637-914d-f85504c06e5b$, UserEmailId:□, Prefix:□, Hash:□, PrimaryKey:□, SecondaryKey:□, SubscriptionStatus:□, SubscriptionScope:□, Creat) START
2024-09-29T07:57:02.063 …ries.ApplicationCosmosAsyncRepositoryV2 DBUG 55cf14750e699f212dfbcaeddf9df77b              7              CosmosDBInsert START
2024-09-29T07:57:02.065 …ries.ApplicationCosmosAsyncRepositoryV2 DBUG 55cf14750e699f212dfbcaeddf9df77b .042m        7               Executing query to create document 'ABB.EDCS.Persistence.Azure.Storage.Documents.ApplicationGrantDocument'.
2024-09-29T07:57:02.067 Diginsight.Diagnostics.$Activity         DBUG 55cf14750e699f212dfbcaeddf9df77b              8                Operation.CreateItemAsync START
2024-09-29T07:57:02.128 Diginsight.Diagnostics.$Activity         DBUG 55cf14750e699f212dfbcaeddf9df77b .071m   60m  8                Operation.CreateItemAsync END
2024-09-29T07:57:02.132 …ries.ApplicationCosmosAsyncRepositoryV2 DBUG 55cf14750e699f212dfbcaeddf9df77b .058m   68m  7              CosmosDBInsert END
2024-09-29T07:57:02.134 …ries.ApplicationCosmosAsyncRepositoryV2 DBUG 55cf14750e699f212dfbcaeddf9df77b .336m        6             Document created with ID '382ae8dd-a46a-4aeb-8ea2-73f0d2f8a73c'.
2024-09-29T07:57:02.137 …ries.ApplicationCosmosAsyncRepositoryV2 DBUG 55cf14750e699f212dfbcaeddf9df77b .255m   82m  6            BaseCosmosDBDataRetriever.CreateDocumentAsync END
2024-09-29T07:57:02.141 …ries.ApplicationCosmosAsyncRepositoryV2 DBUG 55cf14750e699f212dfbcaeddf9df77b .082m  169m  5          ApplicationCosmosAsyncRepositoryV2.GrantPermissionOnPlantAsync END
2024-09-29T07:57:02.152 …ries.ApplicationCosmosAsyncRepositoryV2 DBUG 55cf14750e699f212dfbcaeddf9df77b              5          ApplicationCosmosAsyncRepositoryV2.GrantPermissionOnPlantAsync(applicationId:$3f1a01b9-a251-4a37-a40b-00d965b0158c$, plantId:$a09fe0a1-b981-4e04-aeb5-2fa9ce3a9be1$) START
2024-09-29T07:57:02.163 …ries.ApplicationCosmosAsyncRepositoryV2 DBUG 55cf14750e699f212dfbcaeddf9df77b              6            ApplicationCosmosAsyncRepositoryV2.HasPermissionOnPlantAsync(applicationId:$3f1a01b9-a251-4a37-a40b-00d965b0158c$, plantId:$a09fe0a1-b981-4e04-aeb5-2fa9ce3a9be1$) START
2024-09-29T07:57:02.164 …ries.ApplicationCosmosAsyncRepositoryV2 DBUG 55cf14750e699f212dfbcaeddf9df77b .040m        6             CosmosDB query for class 'ABB.EDCS.Persistence.Azure.Storage.Documents.ApplicationGrantDocument' in database https://testbiotsdkdocdb.documents.azure.com/, collection 'app'
2024-09-29T07:57:02.166 …ries.ApplicationCosmosAsyncRepositoryV2 TRCE 55cf14750e699f212dfbcaeddf9df77b .048m        6             Query: {"query":"SELECT VALUE root FROM root WHERE ((((root[\"ApplicationId\"] = \"3f1a01b9-a251-4a37-a40b-00d965b0158c\") AND (root[\"Type\"] = \"grant-plant\")) AND ((root[\"Target\"] = \"a09fe0a1-b981-4e04-aeb5-2fa9ce3a9be1\") OR (root[\"Target\"] = \"00000000-0000-0000-0000-000000000000\"))) AND (root[\"DeletedDateTime\"] = null))"}
2024-09-29T07:57:02.221 …ries.ApplicationCosmosAsyncRepositoryV2 DBUG 55cf14750e699f212dfbcaeddf9df77b .073m   57m  6            ApplicationCosmosAsyncRepositoryV2.HasPermissionOnPlantAsync END
2024-09-29T07:57:02.258 …ries.ApplicationCosmosAsyncRepositoryV2 DBUG 55cf14750e699f212dfbcaeddf9df77b              6            BaseCosmosDBDataRetriever.CreateDocumentAsync(TKey:Guid, TValue:ApplicationGrantDocument, Document:ApplicationGrantDocument{Id:$caeadff6-db26-4316-998a-970f1515bc0c$, Type:"grant-plant", ApplicationId:$3f1a01b9-a251-4a37-a40b-00d965b0158c$, Target:$a09fe0a1-b981-4e04-aeb5-2fa9ce3a9be1$, UserEmailId:□, Prefix:□, Hash:□, PrimaryKey:□, SecondaryKey:□, SubscriptionStatus:□, SubscriptionScope:□, Creat) START
2024-09-29T07:57:02.265 …ries.ApplicationCosmosAsyncRepositoryV2 DBUG 55cf14750e699f212dfbcaeddf9df77b              7              CosmosDBInsert START
2024-09-29T07:57:02.268 …ries.ApplicationCosmosAsyncRepositoryV2 DBUG 55cf14750e699f212dfbcaeddf9df77b .048m        7               Executing query to create document 'ABB.EDCS.Persistence.Azure.Storage.Documents.ApplicationGrantDocument'.
2024-09-29T07:57:02.270 Diginsight.Diagnostics.$Activity         DBUG 55cf14750e699f212dfbcaeddf9df77b              8                Operation.CreateItemAsync START
2024-09-29T07:57:02.351 Diginsight.Diagnostics.$Activity         DBUG 55cf14750e699f212dfbcaeddf9df77b .288m   78m  8                Operation.CreateItemAsync END
2024-09-29T07:57:02.357 …ries.ApplicationCosmosAsyncRepositoryV2 DBUG 55cf14750e699f212dfbcaeddf9df77b    2m   89m  7              CosmosDBInsert END
2024-09-29T07:57:02.359 …ries.ApplicationCosmosAsyncRepositoryV2 DBUG 55cf14750e699f212dfbcaeddf9df77b .057m        6             Document created with ID 'caeadff6-db26-4316-998a-970f1515bc0c'.
2024-09-29T07:57:02.364 …ries.ApplicationCosmosAsyncRepositoryV2 DBUG 55cf14750e699f212dfbcaeddf9df77b    2m  103m  6            BaseCosmosDBDataRetriever.CreateDocumentAsync END
2024-09-29T07:57:02.367 …ries.ApplicationCosmosAsyncRepositoryV2 DBUG 55cf14750e699f212dfbcaeddf9df77b .053m  215m  5          ApplicationCosmosAsyncRepositoryV2.GrantPermissionOnPlantAsync END
2024-09-29T07:57:02.371 …ervices.Applications.ApplicationService DBUG 55cf14750e699f212dfbcaeddf9df77b .083m 18.1s  4        ApplicationService.CreateApplicationAsync END
2024-09-29T07:57:02.374 …ebAPI.Controllers.ApplicationController DBUG 55cf14750e699f212dfbcaeddf9df77b .179m        3       Application created correctly.
2024-09-29T07:57:02.379 …ebAPI.Controllers.ApplicationController DBUG 55cf14750e699f212dfbcaeddf9df77b .443m 18.1s  3      ApplicationController.CreateApplication END
2024-09-29T07:57:02.413 …iddlewares.ABBContextCreationMiddleware DBUG 55cf14750e699f212dfbcaeddf9df77b .082m 18.5s  2    ABBContextCreationMiddleware.InvokeAsync END
2024-09-29T07:57:02.418 Diginsight.Diagnostics.$Activity         DBUG 55cf14750e699f212dfbcaeddf9df77b .354m 18.6s  1  Microsoft.AspNetCore.Hosting.HttpRequestIn END
