

POST https://localhost:7100/Analysis/GenerateAnalysis
Content-Type: application/json

2024-10-01T09:57:44  Welcome, you are now connected to log-streaming service. The default timeout is 2 hours. Change the timeout with the App Setting SCM_LOGSTREAM_TIMEOUT (in seconds). 
2024-10-01T09:58:45  No new trace in the past 1 min(s).
2024-10-01T09:59:03.234 …2CTokenValidation.LandingCallMiddleware DBUG 1bc36f8d7c340149989c00247b6cc53b              1  LandingCallMiddleware.InvokeAsync(context:DefaultHttpContext{FormOptions:FormOptions{BufferBody:False, MemoryBufferThreshold:65536, BufferBodyLengthLimit:134217728, ValueCountLimit:1024, KeyLengthLimit:2048, ValueLengthLimit:4194304, MultipartBoundaryLengthLimit:128, MultipartHeadersCountLimit:16, MultipartHeadersLengthLimit:16384, Multipar, config:DependencyInjectionExtensions+ProxyClassAwareOptionsMonitor`1{CurrentValue:AzureOptions{ClientId:□, ClientSecret:□, Instance:□, Domain:□, TenantId:□, SDK_ApiScope:□, GrantTypeJWT:□, RequestedTokenUse:□, CylonTreeUrl:□, CylonQueryUrl:□, SubscriptionKey:□, CylonTenentId:□, CylonClientId:□, CylonClient) START
2024-10-01T09:59:03.234 …2CTokenValidation.LandingCallMiddleware DBUG 1bc36f8d7c340149989c00247b6cc53b              1   Request: PUT https://electrificationapi-aps-test-01.azurewebsites.net/api/plant/77903d8a-ba6e-4510-b1bb-d96f415f2120/panel/65c04d76-5ba5-4b68-af35-9644f684f8e4/widget/3ca121b1-f2f8-4710-b662-700089e599b8?plantType=EL
2024-10-01T09:59:03.234 …2CTokenValidation.LandingCallMiddleware DBUG 1bc36f8d7c340149989c00247b6cc53b    6m        1   Assembly Metadata: AzurePipelines/Build.BuildNumber=IntegrationFeatures_24280.2
2024-10-01T09:59:03.234 …2CTokenValidation.LandingCallMiddleware DBUG 1bc36f8d7c340149989c00247b6cc53b   10m        1   Assembly Metadata: AzurePipelines/Build.BuildUri=vstfs:///Build/Build/237641
2024-10-01T09:59:03.234 …2CTokenValidation.LandingCallMiddleware DBUG 1bc36f8d7c340149989c00247b6cc53b    5m        1   Assembly Metadata: AzurePipelines/Build.DefinitionName=NH-CommonBackendApi
2024-10-01T09:59:03.234 …2CTokenValidation.LandingCallMiddleware DBUG 1bc36f8d7c340149989c00247b6cc53b    6m        1   Assembly Metadata: AzurePipelines/Build.Repository.Name=ABB-EL-Common-Backend
2024-10-01T09:59:03.234 …2CTokenValidation.LandingCallMiddleware DBUG 1bc36f8d7c340149989c00247b6cc53b   13m        1   Assembly Metadata: AzurePipelines/Build.Repository.Uri=https://abbsace.visualstudio.com/ABB_Portfolio/_git/ABB-EL-Common-Backend
2024-10-01T09:59:03.234 …2CTokenValidation.LandingCallMiddleware DBUG 1bc36f8d7c340149989c00247b6cc53b    3m        1   Assembly Metadata: AzurePipelines/Build.SourceBranch=refs/heads/IntegrationFeatures
2024-10-01T09:59:03.234 …2CTokenValidation.LandingCallMiddleware DBUG 1bc36f8d7c340149989c00247b6cc53b    5m        1   Assembly Metadata: AzurePipelines/Build.SourceVersion=427da30f3b566afca357dfa2fd65325fd4e065d8
2024-10-01T09:59:03.234 …2CTokenValidation.LandingCallMiddleware DBUG 1bc36f8d7c340149989c00247b6cc53b    5m        1   Assembly Metadata: AzurePipelines/System.CollectionUri=https://abbsace.visualstudio.com/
2024-10-01T09:59:03.234 …2CTokenValidation.LandingCallMiddleware DBUG 1bc36f8d7c340149989c00247b6cc53b    7m        1   Assembly Metadata: AzurePipelines/System.DefinitionId=2426
2024-10-01T09:59:03.234 …2CTokenValidation.LandingCallMiddleware DBUG 1bc36f8d7c340149989c00247b6cc53b    3m        1   Assembly Metadata: AzurePipelines/System.TeamProject=ABB_Portfolio
2024-10-01T09:59:03.234 …vices.PlantWidget.PlantWidgetController DBUG 6d3d8d1e5120fff3f2b12bb7eb5497db              2    PlantWidgetController.Get(plantId:"3ada3be0-5014-4e10-bdf6-e6889f043dc7", widgetId:$6c50ffd9-fc4d-4bfa-990e-86bea2300e3d$, isOptions:True, plantType:"EDCS", isPageEnabled:True, page:1, pageSize:13) START
2024-10-01T09:59:03.271 …n.Api.Adapters.PermissionServiceAdapter DBUG 6d3d8d1e5120fff3f2b12bb7eb5497db   37m        3      PermissionServiceAdapter.GetServiceSubscriptionLicenseResponse(plantId:"3ada3be0-5014-4e10-bdf6-e6889f043dc7", plantType:"EDCS") START
2024-10-01T09:59:03.314 …n.Api.Adapters.PermissionServiceAdapter DBUG 6d3d8d1e5120fff3f2b12bb7eb5497db         43m  3      PermissionServiceAdapter.GetServiceSubscriptionLicenseResponse => ServiceSubscriptionLicenseResponse{Description:"Start Matching Energy Manager", Start:$2022-04-05T00:00:00.0000000+00:00$, End:$2099-12-31T00:00:00.0000000+00:00$, Length:$28394:0:00:00$, Status:Active, MarketplaceUrl:"", ProductServiceId:"P301-SME.SS.P", IsActive:True, IsWarning:False, IsInactive:F END
2024-10-01T09:59:03.335 ….Api.Adapters.PlantWidgetServiceAdapter DBUG 6d3d8d1e5120fff3f2b12bb7eb5497db   20m        3      PlantWidgetServiceAdapter.Get(plantId:"3ada3be0-5014-4e10-bdf6-e6889f043dc7", widgetId:$6c50ffd9-fc4d-4bfa-990e-86bea2300e3d$, plantType:"EDCS", emailId:"TestECDeveloper001@outlook.com", isOptions:True) START
2024-10-01T09:59:03.357 ….Services.PlantWidget.WidgetDataService DBUG 6d3d8d1e5120fff3f2b12bb7eb5497db   22m        4        WidgetDataService.GetDataAsync(plantId:"3ada3be0-5014-4e10-bdf6-e6889f043dc7", plantType:"EDCS", widgetId:$6c50ffd9-fc4d-4bfa-990e-86bea2300e3d$, emailId:"TestECDeveloper001@outlook.com", isOptions:True) START
2024-10-01T09:59:03.377 …sitories.Panel.WidgetCosmosDBRepository DBUG 6d3d8d1e5120fff3f2b12bb7eb5497db   20m        5          WidgetCosmosDBRepository.Get(widgetId:$6c50ffd9-fc4d-4bfa-990e-86bea2300e3d$, plantId:"3ada3be0-5014-4e10-bdf6-e6889f043dc7") START
2024-10-01T09:59:03.397 …sitories.Panel.WidgetCosmosDBRepository DBUG 6d3d8d1e5120fff3f2b12bb7eb5497db   20m        6            BaseCosmosDBDataRetriever`3.GetDocuments(Type:Widget) START
2024-10-01T09:59:03.405 …sitories.Panel.WidgetCosmosDBRepository DBUG 6d3d8d1e5120fff3f2b12bb7eb5497db              6             CosmosDB query for class 'ABB.EL.Common.Core.Panel.Widget' in database https://elcpability-acd-prod-01.documents.azure.com/, collection 'panels'
2024-10-01T09:59:03.413 …sitories.Panel.WidgetCosmosDBRepository TRCE 6d3d8d1e5120fff3f2b12bb7eb5497db    8m        6             Query: {"query":"SELECT VALUE root FROM root WHERE ((root[\"id\"] = \"6c50ffd9-fc4d-4bfa-990e-86bea2300e3d\") AND (root[\"Type\"] = \"Widget\"))"}
2024-10-01T09:59:03.432 …sitories.Panel.WidgetCosmosDBRepository DBUG 6d3d8d1e5120fff3f2b12bb7eb5497db   19m   34m  6            BaseCosmosDBDataRetriever`3.GetDocuments => List<Widget>(1)[Widget{Name:□, Title:"Energy Cost", Status:Active, IsNew:True, Id:$6c50ffd9-fc4d-4bfa-990e-86bea2300e3d$, IsHighlight:False, IsSupportedInAsset:False, IsSupportedInEnergy:False, Sizes:□, TimeInterval:□}] END
2024-10-01T09:59:03.444 …sitories.Panel.WidgetCosmosDBRepository DBUG 6d3d8d1e5120fff3f2b12bb7eb5497db         66m  5          WidgetCosmosDBRepository.Get END
2024-10-01T09:59:03.476 …mplate.WidgetTemplateCosmosDBRepository DBUG 6d3d8d1e5120fff3f2b12bb7eb5497db   31m        5          WidgetTemplateCosmosDBRepository.GetByName(templateName:"EnergyCost", paginationSettings:PaginationSettings{Enabled:False, Page:0, PageSize:□}) START
2024-10-01T09:59:03.529 …mplate.WidgetTemplateCosmosDBRepository DBUG 6d3d8d1e5120fff3f2b12bb7eb5497db         52m  5          WidgetTemplateCosmosDBRepository.GetByName => WidgetTemplate{Name:"EnergyCost", Title:"Energy Cost", Status:Active, IsNew:False, Id:$616755ae-d9f7-46d5-ab92-cebcd633778d$, IsHighlight:False, IsSupportedInAsset:False, IsSupportedInEnergy:True, Sizes:List<WidgetSize>(1)[size1x1], TimeInterval:"900"} END
2024-10-01T09:59:03.548 …ories.UserProfile.UserProfileRepository DBUG 6d3d8d1e5120fff3f2b12bb7eb5497db   20m        5          UserProfileRepository.Get() START
2024-10-01T09:59:03.570 …ories.UserProfile.UserProfileRepository DBUG 6d3d8d1e5120fff3f2b12bb7eb5497db   22m        6            BaseCosmosDBDataRetriever`3.GetDocuments(Type:UserProfile) START
2024-10-01T09:59:03.578 …ories.UserProfile.UserProfileRepository DBUG 6d3d8d1e5120fff3f2b12bb7eb5497db              6             CosmosDB query for class 'ABB.EL.Common.Core.UserProfile.UserProfile' in database https://elcpability-acd-prod-01.documents.azure.com/, collection 'userplant'
2024-10-01T09:59:03.592 …ories.UserProfile.UserProfileRepository TRCE 6d3d8d1e5120fff3f2b12bb7eb5497db   14m        6             Query: {"query":"SELECT VALUE root FROM root WHERE ((LOWER(root[\"EmailId\"]) = \"testecdeveloper001@outlook.com\") AND (root[\"Type\"] = \"UserProfile\"))"}
2024-10-01T09:59:03.624 …ories.UserProfile.UserProfileRepository DBUG 6d3d8d1e5120fff3f2b12bb7eb5497db   33m   52m  6            BaseCosmosDBDataRetriever`3.GetDocuments => List<UserProfile>(1)[UserProfile{Company:"ABB", Name:"TestECDeveloper001", Surname:"EC", Phone:"+393484458924", Culture:en_US, DoW:"Monday", Is24TimeFormat:False, Calender:"Gregorian", DateFormat:"DD/MM/YYYY", Seprator:CommaWithDot, MeasurementUnit:Meter, TempratureUnit:Celsius, SerialValidationFail END
2024-10-01T09:59:03.635 …ories.UserProfile.UserProfileRepository DBUG 6d3d8d1e5120fff3f2b12bb7eb5497db         85m  5          UserProfileRepository.Get END
2024-10-01T09:59:03.656 …erProfile.UserProfileCosmosDBRepository DBUG 6d3d8d1e5120fff3f2b12bb7eb5497db   21m        5          BaseCosmosDBDataRetriever`3.GetDocuments(Type:UnitConversionData) START
2024-10-01T09:59:03.665 …erProfile.UserProfileCosmosDBRepository DBUG 6d3d8d1e5120fff3f2b12bb7eb5497db              5           CosmosDB query for class 'ABB.EL.Common.Core.UserProfile.UnitConversion.UnitConversionData' in database https://elcpability-acd-prod-01.documents.azure.com/, collection 'panels'
2024-10-01T09:59:03.674 …erProfile.UserProfileCosmosDBRepository TRCE 6d3d8d1e5120fff3f2b12bb7eb5497db    9m        5           Query: {"query":"SELECT VALUE root FROM root WHERE (root[\"Type\"] = \"UnitMapping\")"}
2024-10-01T09:59:03.709 …erProfile.UserProfileCosmosDBRepository DBUG 6d3d8d1e5120fff3f2b12bb7eb5497db   35m   51m  5          BaseCosmosDBDataRetriever`3.GetDocuments => List<UnitConversionData>(1)[UnitConversionData{Type:"UnitMapping", Status:"Active", DateCreated:$2021-04-05T18:18:15.6658082Z$, DateModified:$2021-04-05T18:24:57.7213266Z$, Temperature:List<Units>(2)[Units{Name:"Celsius", MappedUnit:List<string>(3)["c", "°c", "celius"]}, Units{Name:"Fahrenheit", Map END
2024-10-01T09:59:03.725 ….Services.PlantWidget.WidgetDataService DBUG 6d3d8d1e5120fff3f2b12bb7eb5497db   16m        5          WidgetDataService.GetData START
2024-10-01T09:59:03.733 ….Services.PlantWidget.WidgetDataService DBUG 6d3d8d1e5120fff3f2b12bb7eb5497db              5           widget.Template: 'EnergyCost', isWidgetSupported: True
2024-10-01T09:59:03.754 …EL.Common.Services.ELPlants.ExternalIds DBUG 6d3d8d1e5120fff3f2b12bb7eb5497db   21m        6            ExternalIds.GetEDCSPlantIdForELPlant(plantType:"EDCS", plantId:"3ada3be0-5014-4e10-bdf6-e6889f043dc7", emailId:"TestECDeveloper001@outlook.com", paginationSettings:PaginationSettings{Enabled:True, Page:1, PageSize:13}) START
2024-10-01T09:59:03.765 …EL.Common.Services.ELPlants.ExternalIds DBUG 6d3d8d1e5120fff3f2b12bb7eb5497db         11m  6            ExternalIds.GetEDCSPlantIdForELPlant END
2024-10-01T09:59:03.790 ….Services.PlantWidget.EnergyCostService DBUG 6d3d8d1e5120fff3f2b12bb7eb5497db   25m        6            EnergyCostService.GetEnergyCostData(plantId:$3ada3be0-5014-4e10-bdf6-e6889f043dc7$, widgetId:$6c50ffd9-fc4d-4bfa-990e-86bea2300e3d$, emailId:"TestECDeveloper001@outlook.com", widgetSettings:"{"period":"CurrentMonth","parentCurrentPageIndex":…", isOptions:True) START
2024-10-01T09:59:03.815 …s.PaginatedReadOnlyPlantAsyncRepository DBUG 6d3d8d1e5120fff3f2b12bb7eb5497db   25m        7              PaginatedReadOnlyPlantAsyncRepository.GetUserPlant(email:"TestECDeveloper001@outlook.com", plantId:$3ada3be0-5014-4e10-bdf6-e6889f043dc7$) START
2024-10-01T09:59:03.861 …s.PaginatedReadOnlyPlantAsyncRepository DBUG 6d3d8d1e5120fff3f2b12bb7eb5497db         41m  7              PaginatedReadOnlyPlantAsyncRepository.GetUserPlant END
2024-10-01T09:59:04.389 ….Services.PlantWidget.EnergyCostService DBUG 6d3d8d1e5120fff3f2b12bb7eb5497db        597m  6            EnergyCostService.GetEnergyCostData ‼ END
2024-10-01T09:59:04.400 ….Services.PlantWidget.WidgetDataService DBUG 6d3d8d1e5120fff3f2b12bb7eb5497db   11m  673m  5          WidgetDataService.GetData ‼ END
2024-10-01T09:59:04.411 ….Services.PlantWidget.WidgetDataService DBUG 6d3d8d1e5120fff3f2b12bb7eb5497db       1053m  4        WidgetDataService.GetDataAsync ‼ END
2024-10-01T09:59:04.419 ….Api.Adapters.PlantWidgetServiceAdapter EROR 6d3d8d1e5120fff3f2b12bb7eb5497db              3       Exception getting widget data
System.NullReferenceException: Object reference not set to an instance of an object.
   at ABB.BIoT.Common.Pattern.Adapters.Query.Implementations.BaseQueryAdapter.<>c__15`1.<AddEmptyData>b__15_5(T x)
   at System.Linq.EnumerableSorter`2.ComputeKeys(TElement[] elements, Int32 count)
   at System.Linq.EnumerableSorter`1.ComputeMap(TElement[] elements, Int32 count)
   at System.Linq.OrderedEnumerable`1.ToArray()
   at ABB.BIoT.Common.Pattern.Adapters.Query.Implementations.BaseQueryAdapter.AddEmptyData[T](IEnumerable`1 ids, DateTimeOffset start, DateTimeOffset end, AggregationRange range, IEnumerable`1 data, Dictionary`2 timeZoneInfos, Func`3 map)
   at ABB.BIoT.Common.Pattern.Adapters.Query.Implementations.BaseQueryAdapter.AddEmptyData[T](Dictionary`2 ids, DateTimeOffset start, DateTimeOffset end, AggregationRange range, IEnumerable`1 data, Dictionary`2 offsets, Func`3 map)
   at ABB.BIoT.Common.Pattern.Adapters.Query.Implementations.EquipmentQueryAdapter.<>c__DisplayClass9_0.<<GetEnergyCostByEquipmentAsync>g__GetAggregatedValues|4>d.MoveNext()
--- End of stack trace from previous location ---
   at ABB.BIoT.Common.Pattern.Adapters.Query.Implementations.EquipmentQueryAdapter.GetEnergyCostByEquipmentAsync(IEnumerable`1 equipmentIds, DateTimeOffset start, DateTimeOffset end, AggregationRange range, Dictionary`2 timeZoneInfos)
   at ABB.BIoT.Common.Pattern.Adapters.Query.Implementations.EquipmentQueryAdapter.GetEnergyCostAsync(IEnumerable`1 equipmentIds, DateTimeOffset start, DateTimeOffset end)
   at ABB.BIoT.Common.Pattern.Adapters.Query.Implementations.GroupQueryAdapter.GetEnergyCostAsync(IEnumerable`1 groups, DateTimeOffset start, DateTimeOffset end, Boolean includeOnlySignedItems)
   at ABB.BIoT.Common.Pattern.Adapters.WidgetsQuery.Implementations.WidgetQueryAdapter.GetEnergyCostAsync(IEnumerable`1 groups, DateTimeOffset start, DateTimeOffset end)
   at ABB.EL.Common.Storage.BIoTCommon.Repositories.Widgets.EnergyCostRepository.GetEnergyCostSummaryData(Guid plantId, EnergyCostData data, IEnumerable`1 equipments, PaginationSettings paginationSettings, CancellationToken cancellationToken) in D:\a\1\s\ABB.EL.Common.Storage.BIoTCommon\Repositories\Widgets\EnergyCostRepository.cs:line 55
   at ABB.EL.Common.Services.PlantWidget.EnergyCostService.GetEnergyCostData(Guid plantId, Guid widgetId, String emailId, Boolean isOptions, String widgetSettings, UserProfile userProfile, ContextBase context, CancellationToken cancellationToken) in D:\a\1\s\ABB.EL.Common.Services\WidgetData\EnergyCostService.cs:line 83
   at ABB.EL.Common.Services.PlantWidget.WidgetDataService.GetDataAsync(String plantId, String plantType, Guid widgetId, String emailId, Boolean isOptions, ContextBase context, CancellationToken cancellationToken) in D:\a\1\s\ABB.EL.Common.Services\WidgetData\WidgetDataService.cs:line 496
   at ABB.EL.Common.Api.Adapters.PlantWidgetServiceAdapter.Get(String plantId, Guid widgetId, String plantType, String emailId, Boolean isOptions, ContextBase context) in D:\a\1\s\ABB.EL.Common.Api\Adapters\PlantWidgetServiceAdapter.cs:line 75
2024-10-01T09:59:04.431 ….Api.Adapters.PlantWidgetServiceAdapter DBUG 6d3d8d1e5120fff3f2b12bb7eb5497db   12m 1095m  3      PlantWidgetServiceAdapter.Get ‼ END
2024-10-01T09:59:04.442 …vices.PlantWidget.PlantWidgetController DBUG 6d3d8d1e5120fff3f2b12bb7eb5497db       1225m  2    PlantWidgetController
2024-10-01T09:59:04.443 …2CTokenValidation.LandingCallMiddleware DBUG 1bc36f8d7c340149989c00247b6cc53b   10m  601m  1  LandingCallMiddleware.InvokeAsync




POST https://localhost:7100/Analysis/GenerateAnalysis
Content-Type: application/json

2024-10-01T10:14:48.374 …vices.PlantWidget.PlantWidgetController DBUG 6ebbcf5efd2a299180a68635cfc17134              2    PlantWidgetController.Get(plantId:"3ada3be0-5014-4e10-bdf6-e6889f043dc7", widgetId:$6c50ffd9-fc4d-4bfa-990e-86bea2300e3d$, isOptions:True, plantType:"EDCS", isPageEnabled:True, page:1, pageSize:13) START
2024-10-01T10:14:48.405 …n.Api.Adapters.PermissionServiceAdapter DBUG 6ebbcf5efd2a299180a68635cfc17134   31m        3      PermissionServiceAdapter.GetServiceSubscriptionLicenseResponse(plantId:"3ada3be0-5014-4e10-bdf6-e6889f043dc7", plantType:"EDCS") START
2024-10-01T10:14:48.453 …n.Api.Adapters.PermissionServiceAdapter DBUG 6ebbcf5efd2a299180a68635cfc17134         48m  3      PermissionServiceAdapter.GetServiceSubscriptionLicenseResponse => ServiceSubscriptionLicenseResponse{Description:"Start Matching Energy Manager", Start:$2022-04-05T00:00:00.0000000+00:00$, End:$2099-12-31T00:00:00.0000000+00:00$, Length:$28394:0:00:00$, Status:Active, MarketplaceUrl:"", ProductServiceId:"P301-SME.SS.P", IsActive:True, IsWarning:False, IsInactive:F END
2024-10-01T10:14:48.475 ….Api.Adapters.PlantWidgetServiceAdapter DBUG 6ebbcf5efd2a299180a68635cfc17134   22m        3      PlantWidgetServiceAdapter.Get(plantId:"3ada3be0-5014-4e10-bdf6-e6889f043dc7", widgetId:$6c50ffd9-fc4d-4bfa-990e-86bea2300e3d$, plantType:"EDCS", emailId:"TestECDeveloper001@outlook.com", isOptions:True) START
2024-10-01T10:14:48.494 ….Services.PlantWidget.WidgetDataService DBUG 6ebbcf5efd2a299180a68635cfc17134   19m        4        WidgetDataService.GetDataAsync(plantId:"3ada3be0-5014-4e10-bdf6-e6889f043dc7", plantType:"EDCS", widgetId:$6c50ffd9-fc4d-4bfa-990e-86bea2300e3d$, emailId:"TestECDeveloper001@outlook.com", isOptions:True) START
2024-10-01T10:14:48.518 …sitories.Panel.WidgetCosmosDBRepository DBUG 6ebbcf5efd2a299180a68635cfc17134   24m        5          WidgetCosmosDBRepository.Get(widgetId:$6c50ffd9-fc4d-4bfa-990e-86bea2300e3d$, plantId:"3ada3be0-5014-4e10-bdf6-e6889f043dc7") START
2024-10-01T10:14:48.537 …sitories.Panel.WidgetCosmosDBRepository DBUG 6ebbcf5efd2a299180a68635cfc17134   19m        6            BaseCosmosDBDataRetriever`3.GetDocuments(Type:Widget) START
2024-10-01T10:14:48.544 …sitories.Panel.WidgetCosmosDBRepository DBUG 6ebbcf5efd2a299180a68635cfc17134              6             CosmosDB query for class 'ABB.EL.Common.Core.Panel.Widget' in database https://elcpability-acd-prod-01.documents.azure.com/, collection 'panels'
2024-10-01T10:14:48.558 …sitories.Panel.WidgetCosmosDBRepository TRCE 6ebbcf5efd2a299180a68635cfc17134   14m        6             Query: {"query":"SELECT VALUE root FROM root WHERE ((root[\"id\"] = \"6c50ffd9-fc4d-4bfa-990e-86bea2300e3d\") AND (root[\"Type\"] = \"Widget\"))"}
2024-10-01T10:14:48.578 …sitories.Panel.WidgetCosmosDBRepository DBUG 6ebbcf5efd2a299180a68635cfc17134   20m   39m  6            BaseCosmosDBDataRetriever`3.GetDocuments => List<Widget>(1)[Widget{Name:□, Title:"Energy Cost", Status:Active, IsNew:True, Id:$6c50ffd9-fc4d-4bfa-990e-86bea2300e3d$, IsHighlight:False, IsSupportedInAsset:False, IsSupportedInEnergy:False, Sizes:□, TimeInterval:□}] END
2024-10-01T10:14:48.589 …sitories.Panel.WidgetCosmosDBRepository DBUG 6ebbcf5efd2a299180a68635cfc17134         68m  5          WidgetCosmosDBRepository.Get END
2024-10-01T10:14:48.605 …mplate.WidgetTemplateCosmosDBRepository DBUG 6ebbcf5efd2a299180a68635cfc17134   17m        5          WidgetTemplateCosmosDBRepository.GetByName(templateName:"EnergyCost", paginationSettings:PaginationSettings{Enabled:False, Page:0, PageSize:□}) START
2024-10-01T10:14:48.645 …mplate.WidgetTemplateCosmosDBRepository DBUG 6ebbcf5efd2a299180a68635cfc17134         38m  5          WidgetTemplateCosmosDBRepository.GetByName => WidgetTemplate{Name:"EnergyCost", Title:"Energy Cost", Status:Active, IsNew:False, Id:$616755ae-d9f7-46d5-ab92-cebcd633778d$, IsHighlight:False, IsSupportedInAsset:False, IsSupportedInEnergy:True, Sizes:List<WidgetSize>(1)[size1x1], TimeInterval:"900"} END
2024-10-01T10:14:48.664 …ories.UserProfile.UserProfileRepository DBUG 6ebbcf5efd2a299180a68635cfc17134   19m        5          UserProfileRepository.Get() START
2024-10-01T10:14:48.693 …ories.UserProfile.UserProfileRepository DBUG 6ebbcf5efd2a299180a68635cfc17134   29m        6            BaseCosmosDBDataRetriever`3.GetDocuments(Type:UserProfile) START
2024-10-01T10:14:48.700 …ories.UserProfile.UserProfileRepository DBUG 6ebbcf5efd2a299180a68635cfc17134              6             CosmosDB query for class 'ABB.EL.Common.Core.UserProfile.UserProfile' in database https://elcpability-acd-prod-01.documents.azure.com/, collection 'userplant'
2024-10-01T10:14:48.710 …ories.UserProfile.UserProfileRepository TRCE 6ebbcf5efd2a299180a68635cfc17134   11m        6             Query: {"query":"SELECT VALUE root FROM root WHERE ((LOWER(root[\"EmailId\"]) = \"testecdeveloper001@outlook.com\") AND (root[\"Type\"] = \"UserProfile\"))"}
2024-10-01T10:14:48.738 …ories.UserProfile.UserProfileRepository DBUG 6ebbcf5efd2a299180a68635cfc17134   27m   44m  6            BaseCosmosDBDataRetriever`3.GetDocuments => List<UserProfile>(1)[UserProfile{Company:"ABB", Name:"TestECDeveloper001", Surname:"EC", Phone:"+393484458924", Culture:en_US, DoW:"Monday", Is24TimeFormat:False, Calender:"Gregorian", DateFormat:"DD/MM/YYYY", Seprator:CommaWithDot, MeasurementUnit:Meter, TempratureUnit:Celsius, SerialValidationFail END
2024-10-01T10:14:48.748 …ories.UserProfile.UserProfileRepository DBUG 6ebbcf5efd2a299180a68635cfc17134         83m  5          UserProfileRepository.Get END
2024-10-01T10:14:48.765 …erProfile.UserProfileCosmosDBRepository DBUG 6ebbcf5efd2a299180a68635cfc17134   17m        5          BaseCosmosDBDataRetriever`3.GetDocuments(Type:UnitConversionData) START
2024-10-01T10:14:48.772 …erProfile.UserProfileCosmosDBRepository DBUG 6ebbcf5efd2a299180a68635cfc17134              5           CosmosDB query for class 'ABB.EL.Common.Core.UserProfile.UnitConversion.UnitConversionData' in database https://elcpability-acd-prod-01.documents.azure.com/, collection 'panels'
2024-10-01T10:14:48.789 …erProfile.UserProfileCosmosDBRepository TRCE 6ebbcf5efd2a299180a68635cfc17134   17m        5           Query: {"query":"SELECT VALUE root FROM root WHERE (root[\"Type\"] = \"UnitMapping\")"}
2024-10-01T10:14:48.816 …erProfile.UserProfileCosmosDBRepository DBUG 6ebbcf5efd2a299180a68635cfc17134   27m   49m  5          BaseCosmosDBDataRetriever`3.GetDocuments => List<UnitConversionData>(1)[UnitConversionData{Type:"UnitMapping", Status:"Active", DateCreated:$2021-04-05T18:18:15.6658082Z$, DateModified:$2021-04-05T18:24:57.7213266Z$, Temperature:List<Units>(2)[Units{Name:"Celsius", MappedUnit:List<string>(3)["c", "°c", "celius"]}, Units{Name:"Fahrenheit", Map END
2024-10-01T10:14:48.831 ….Services.PlantWidget.WidgetDataService DBUG 6ebbcf5efd2a299180a68635cfc17134   15m        5          WidgetDataService.GetData START
2024-10-01T10:14:48.838 ….Services.PlantWidget.WidgetDataService DBUG 6ebbcf5efd2a299180a68635cfc17134              5           widget.Template: 'EnergyCost', isWidgetSupported: True
2024-10-01T10:14:48.858 …EL.Common.Services.ELPlants.ExternalIds DBUG 6ebbcf5efd2a299180a68635cfc17134   20m        6            ExternalIds.GetEDCSPlantIdForELPlant(plantType:"EDCS", plantId:"3ada3be0-5014-4e10-bdf6-e6889f043dc7", emailId:"TestECDeveloper001@outlook.com", paginationSettings:PaginationSettings{Enabled:True, Page:1, PageSize:13}) START
2024-10-01T10:14:48.869 …EL.Common.Services.ELPlants.ExternalIds DBUG 6ebbcf5efd2a299180a68635cfc17134         10m  6            ExternalIds.GetEDCSPlantIdForELPlant END
2024-10-01T10:14:48.887 ….Services.PlantWidget.EnergyCostService DBUG 6ebbcf5efd2a299180a68635cfc17134   18m        6            EnergyCostService.GetEnergyCostData(plantId:$3ada3be0-5014-4e10-bdf6-e6889f043dc7$, widgetId:$6c50ffd9-fc4d-4bfa-990e-86bea2300e3d$, emailId:"TestECDeveloper001@outlook.com", widgetSettings:"{"period":"CurrentMonth","parentCurrentPageIndex":…", isOptions:True) START
2024-10-01T10:14:48.913 …s.PaginatedReadOnlyPlantAsyncRepository DBUG 6ebbcf5efd2a299180a68635cfc17134   26m        7              PaginatedReadOnlyPlantAsyncRepository.GetUserPlant(email:"TestECDeveloper001@outlook.com", plantId:$3ada3be0-5014-4e10-bdf6-e6889f043dc7$) START
2024-10-01T10:14:48.949 …s.PaginatedReadOnlyPlantAsyncRepository DBUG 6ebbcf5efd2a299180a68635cfc17134         35m  7              PaginatedReadOnlyPlantAsyncRepository.GetUserPlant END
2024-10-01T10:14:49.424 ….Services.PlantWidget.EnergyCostService DBUG 6ebbcf5efd2a299180a68635cfc17134        536m  6            EnergyCostService.GetEnergyCostData ‼ END
2024-10-01T10:14:49.436 ….Services.PlantWidget.WidgetDataService DBUG 6ebbcf5efd2a299180a68635cfc17134   12m  603m  5          WidgetDataService.GetData ‼ END
2024-10-01T10:14:49.446 ….Services.PlantWidget.WidgetDataService DBUG 6ebbcf5efd2a299180a68635cfc17134        951m  4        WidgetDataService.GetDataAsync ‼ END
2024-10-01T10:14:49.463 ….Api.Adapters.PlantWidgetServiceAdapter EROR 6ebbcf5efd2a299180a68635cfc17134              3       Exception getting widget data
System.NullReferenceException: Object reference not set to an instance of an object.
   at ABB.BIoT.Common.Pattern.Adapters.Query.Implementations.BaseQueryAdapter.<>c__15`1.<AddEmptyData>b__15_5(T x)
   at System.Linq.EnumerableSorter`2.ComputeKeys(TElement[] elements, Int32 count)
   at System.Linq.EnumerableSorter`1.ComputeMap(TElement[] elements, Int32 count)
   at System.Linq.OrderedEnumerable`1.ToArray()
   at ABB.BIoT.Common.Pattern.Adapters.Query.Implementations.BaseQueryAdapter.AddEmptyData[T](IEnumerable`1 ids, DateTimeOffset start, DateTimeOffset end, AggregationRange range, IEnumerable`1 data, Dictionary`2 timeZoneInfos, Func`3 map)
   at ABB.BIoT.Common.Pattern.Adapters.Query.Implementations.BaseQueryAdapter.AddEmptyData[T](Dictionary`2 ids, DateTimeOffset start, DateTimeOffset end, AggregationRange range, IEnumerable`1 data, Dictionary`2 offsets, Func`3 map)
   at ABB.BIoT.Common.Pattern.Adapters.Query.Implementations.EquipmentQueryAdapter.<>c__DisplayClass9_0.<<GetEnergyCostByEquipmentAsync>g__GetAggregatedValues|4>d.MoveNext()
--- End of stack trace from previous location ---
   at ABB.BIoT.Common.Pattern.Adapters.Query.Implementations.EquipmentQueryAdapter.GetEnergyCostByEquipmentAsync(IEnumerable`1 equipmentIds, DateTimeOffset start, DateTimeOffset end, AggregationRange range, Dictionary`2 timeZoneInfos)
   at ABB.BIoT.Common.Pattern.Adapters.Query.Implementations.EquipmentQueryAdapter.GetEnergyCostAsync(IEnumerable`1 equipmentIds, DateTimeOffset start, DateTimeOffset end)
   at ABB.BIoT.Common.Pattern.Adapters.Query.Implementations.GroupQueryAdapter.GetEnergyCostAsync(IEnumerable`1 groups, DateTimeOffset start, DateTimeOffset end, Boolean includeOnlySignedItems)
   at ABB.BIoT.Common.Pattern.Adapters.WidgetsQuery.Implementations.WidgetQueryAdapter.GetEnergyCostAsync(IEnumerable`1 groups, DateTimeOffset start, DateTimeOffset end)
   at ABB.EL.Common.Storage.BIoTCommon.Repositories.Widgets.EnergyCostRepository.GetEnergyCostSummaryData(Guid plantId, EnergyCostData data, IEnumerable`1 equipments, PaginationSettings paginationSettings, CancellationToken cancellationToken) in D:\a\1\s\ABB.EL.Common.Storage.BIoTCommon\Repositories\Widgets\EnergyCostRepository.cs:line 55
   at ABB.EL.Common.Services.PlantWidget.EnergyCostService.GetEnergyCostData(Guid plantId, Guid widgetId, String emailId, Boolean isOptions, String widgetSettings, UserProfile userProfile, ContextBase context, CancellationToken cancellationToken) in D:\a\1\s\ABB.EL.Common.Services\WidgetData\EnergyCostService.cs:line 83
   at ABB.EL.Common.Services.PlantWidget.WidgetDataService.GetDataAsync(String plantId, String plantType, Guid widgetId, String emailId, Boolean isOptions, ContextBase context, CancellationToken cancellationToken) in D:\a\1\s\ABB.EL.Common.Services\WidgetData\WidgetDataService.cs:line 496
   at ABB.EL.Common.Api.Adapters.PlantWidgetServiceAdapter.Get(String plantId, Guid widgetId, String plantType, String emailId, Boolean isOptions, ContextBase context) in D:\a\1\s\ABB.EL.Common.Api\Adapters\PlantWidgetServiceAdapter.cs:line 75
2024-10-01T10:14:49.473 ….Api.Adapters.PlantWidgetServiceAdapter DBUG 6ebbcf5efd2a299180a68635cfc17134   10m 1000m  3      PlantWidgetServiceAdapter.Get ‼ END
2024-10-01T10:14:49.483 …vices.PlantWidget.PlantWidgetController DBUG 6ebbcf5efd2a299180a68635cfc17134       1124m  2    PlantWidgetController





POST https://localhost:7100/Analysis/GenerateAnalysis
Content-Type: application/json

2024-10-01T12:11:26.872 Diginsight.Diagnostics.$Activity         DBUG c81e69d7200a66755d8b04859fb30387              1  Microsoft.AspNetCore.Hosting.HttpRequestIn START
2024-10-01T12:11:26.922 …iddlewares.ABBContextCreationMiddleware DBUG c81e69d7200a66755d8b04859fb30387              2    ABBContextCreationMiddleware.InvokeAsync(Method:"GET", Path:PathString{Value:"/api/bc21f6c0-772c-4863-90be-5bfce8ded826/plants/7…", HasValue:True}) START
2024-10-01T12:11:26.929 …iddlewares.ABBContextCreationMiddleware DBUG c81e69d7200a66755d8b04859fb30387              3      ABBContextCreationMiddleware.CreateABBContext() START
2024-10-01T12:11:26.932 …iddlewares.ABBContextCreationMiddleware DBUG c81e69d7200a66755d8b04859fb30387 .451m    3m  3      ABBContextCreationMiddleware.CreateABBContext END
2024-10-01T12:11:26.952 …WebAPI.Program+SdkAuthenticationHandler DBUG c81e69d7200a66755d8b04859fb30387              3      SdkAuthenticationHandler.HandleAuthenticateAsync() START
2024-10-01T12:11:26.956 …WebAPI.Program+SdkAuthenticationHandler DBUG c81e69d7200a66755d8b04859fb30387              4        CoreAuthenticateAsync(scheme:"Bearer") START
2024-10-01T12:11:26.959 …WebAPI.Program+SdkAuthenticationHandler DBUG c81e69d7200a66755d8b04859fb30387 .049m    2m  4        CoreAuthenticateAsync => □ END
2024-10-01T12:11:26.963 …WebAPI.Program+SdkAuthenticationHandler DBUG c81e69d7200a66755d8b04859fb30387              4        CoreAuthenticateAsync(scheme:"ApiKeyWithPrefix") START
2024-10-01T12:11:26.970 …y.ApiKeyWithPrefixAuthenticationHandler DBUG c81e69d7200a66755d8b04859fb30387              5          ApiKeyWithPrefixAuthenticationHandler.HandleAuthenticateAsync() START
2024-10-01T12:11:26.972 …y.ApiKeyWithPrefixAuthenticationHandler DBUG c81e69d7200a66755d8b04859fb30387 .056m        5           HeaderKey: ABB 
2024-10-01T12:11:26.974 …y.ApiKeyWithPrefixAuthenticationHandler DBUG c81e69d7200a66755d8b04859fb30387 .245m        5           HeaderValue: ABB TP+Xs+MCkubX8pDsL4hf3U8t3y0kQCZlIA==
2024-10-01T12:11:26.982 …iness.Services.Security.SecurityService DBUG c81e69d7200a66755d8b04859fb30387              6            SecurityService.CheckApiKeyAsync(apikey:"TP+Xs+MCkubX8pDsL4hf3U8t3y0kQCZlIA==") START
2024-10-01T12:11:26.987 …ositories.ApiKeyCosmosAsyncRepositoryV2 DBUG c81e69d7200a66755d8b04859fb30387              7              ApiKeyCosmosAsyncRepositoryV2.ValidateApiKeyAsync(apikey:"TP+Xs+MCkubX8pDsL4hf3U8t3y0kQCZlIA==") START
2024-10-01T12:11:26.990 …ositories.ApiKeyCosmosAsyncRepositoryV2 DBUG c81e69d7200a66755d8b04859fb30387 .881m        7               CosmosDB query for class 'ABB.EDCS.Persistence.Azure.Storage.Documents.ApiKeyDocument' in database https://elsdk-acd-stage-01.documents.azure.com/, collection 'app'
2024-10-01T12:11:26.992 …ositories.ApiKeyCosmosAsyncRepositoryV2 TRCE c81e69d7200a66755d8b04859fb30387 .380m        7               Query: {"query":"SELECT VALUE root FROM root WHERE (((((root[\"ApplicationId\"] = \"bc21f6c0-772c-4863-90be-5bfce8ded826\") AND (root[\"Type\"] = \"apikey\")) AND (root[\"Prefix\"] = \"TP+Xs+\")) AND (root[\"Hash\"] = \"4C64B08C78E5DE46C159BA0F5C2FFF5EB7697482AA8A919D418F62742455D33F\")) AND (root[\"DeletedDateTime\"] = null))"}
2024-10-01T12:11:27.350 …ositories.ApiKeyCosmosAsyncRepositoryV2 DBUG c81e69d7200a66755d8b04859fb30387 .098m  355m  7              ApiKeyCosmosAsyncRepositoryV2.ValidateApiKeyAsync END
2024-10-01T12:11:27.355 …iness.Services.Security.SecurityService DBUG c81e69d7200a66755d8b04859fb30387 .073m  373m  6            SecurityService.CheckApiKeyAsync END
2024-10-01T12:11:27.374 …iness.Services.Security.SecurityService DBUG c81e69d7200a66755d8b04859fb30387              6            SecurityService.GetApiKeyScopesAsync(apikey:"TP+Xs+MCkubX8pDsL4hf3U8t3y0kQCZlIA==") START
2024-10-01T12:11:27.391 …ositories.ApiKeyCosmosAsyncRepositoryV2 DBUG c81e69d7200a66755d8b04859fb30387              7              ApiKeyCosmosAsyncRepositoryV2.GetApiKeyScopesAsync(apikey:"TP+Xs+MCkubX8pDsL4hf3U8t3y0kQCZlIA==") START
2024-10-01T12:11:27.410 …ositories.ApiKeyCosmosAsyncRepositoryV2 DBUG c81e69d7200a66755d8b04859fb30387              8                BaseCosmosDBDataRetriever.GetFirstDocumentOrderedAsync(TValue:ApiKeyDocument) START
2024-10-01T12:11:27.414 …ositories.ApiKeyCosmosAsyncRepositoryV2 DBUG c81e69d7200a66755d8b04859fb30387 .532m        8                 CosmosDB query for class 'ABB.EDCS.Persistence.Azure.Storage.Documents.ApiKeyDocument' in database https://elsdk-acd-stage-01.documents.azure.com/, collection 'app'
2024-10-01T12:11:27.417 …ositories.ApiKeyCosmosAsyncRepositoryV2 TRCE c81e69d7200a66755d8b04859fb30387 .058m        8                 Query: {"query":"SELECT TOP 1 VALUE root FROM root WHERE ((((root[\"ApplicationId\"] = \"bc21f6c0-772c-4863-90be-5bfce8ded826\") AND (root[\"Type\"] = \"apikey\")) AND (root[\"Prefix\"] = \"TP+Xs+\")) AND (root[\"DeletedDateTime\"] = null))"}
2024-10-01T12:11:27.422 Diginsight.Diagnostics.$Activity         DBUG c81e69d7200a66755d8b04859fb30387              9                  Operation.Typed FeedIterator ReadNextAsync START
2024-10-01T12:11:27.693 Diginsight.Diagnostics.$Activity         DBUG c81e69d7200a66755d8b04859fb30387 .093m  271m  9                  Operation.Typed FeedIterator ReadNextAsync END
2024-10-01T12:11:27.696 …ositories.ApiKeyCosmosAsyncRepositoryV2 DBUG c81e69d7200a66755d8b04859fb30387 .064m        8                 Query executed successfully. Retrieved 1 documents of type 'ABB.EDCS.Persistence.Azure.Storage.Documents.ApiKeyDocument'.
2024-10-01T12:11:27.702 …ositories.ApiKeyCosmosAsyncRepositoryV2 DBUG c81e69d7200a66755d8b04859fb30387 .297m  291m  8                BaseCosmosDBDataRetriever.GetFirstDocumentOrderedAsync END
2024-10-01T12:11:27.706 …ositories.ApiKeyCosmosAsyncRepositoryV2 DBUG c81e69d7200a66755d8b04859fb30387 .224m  315m  7              ApiKeyCosmosAsyncRepositoryV2.GetApiKeyScopesAsync END
2024-10-01T12:11:27.715 …iness.Services.Security.SecurityService DBUG c81e69d7200a66755d8b04859fb30387    2m  338m  6            SecurityService.GetApiKeyScopesAsync END
2024-10-01T12:11:27.724 …y.ApiKeyWithPrefixAuthenticationHandler DBUG c81e69d7200a66755d8b04859fb30387    6m        5           Authenticated application.
2024-10-01T12:11:27.735 …y.ApiKeyWithPrefixAuthenticationHandler DBUG c81e69d7200a66755d8b04859fb30387    5m  759m  5          ApiKeyWithPrefixAuthenticationHandler.HandleAuthenticateAsync END
2024-10-01T12:11:27.739 …y.ApiKeyWithPrefixAuthenticationHandler DBUG c81e69d7200a66755d8b04859fb30387 .067m        4         AuthenticationScheme: ApiKeyWithPrefix was successfully authenticated.
2024-10-01T12:11:28.108 …WebAPI.Program+SdkAuthenticationHandler DBUG c81e69d7200a66755d8b04859fb30387 .171m  779m  4        CoreAuthenticateAsync => AuthenticateResult{Succeeded:True, Ticket:AuthenticationTicket{AuthenticationScheme:"ApiKeyWithPrefix", Principal:ClaimsPrincipal{Claims:ClaimsPrincipal+<get_Claims>d__22[Claim{…}, …], …}, …}, …} END
2024-10-01T12:11:28.388 …WebAPI.Program+SdkAuthenticationHandler DBUG c81e69d7200a66755d8b04859fb30387 .106m 1160m  3      SdkAuthenticationHandler.HandleAuthenticateAsync => AuthenticateResult{Succeeded:True, Ticket:AuthenticationTicket{AuthenticationScheme:"ApiKeyWithPrefix", Principal:ClaimsPrincipal{Claims:ClaimsPrincipal+<get_Claims>d__22[Claim{Issuer:"LOCAL AUTHORITY", OriginalIssuer:"LOCAL AUTHORITY", Properties:», Subject:», Type:"http://schemas.microsoft.com/ws/ END
2024-10-01T12:11:28.393 …WebAPI.Program+SdkAuthenticationHandler DBUG c81e69d7200a66755d8b04859fb30387 .920m        2     AuthenticationScheme: Sdk was successfully authenticated.
2024-10-01T12:11:28.452 …CS.WebAPI.Controllers.DevicesController DBUG c81e69d7200a66755d8b04859fb30387              3      DevicesController.GetPlantDevicesAsync(applicationId:$bc21f6c0-772c-4863-90be-5bfce8ded826$, plantId:$77903d8a-ba6e-4510-b1bb-d96f415f2120$, page:1) START
2024-10-01T12:11:28.482 …ries.ApplicationCosmosAsyncRepositoryV2 DBUG c81e69d7200a66755d8b04859fb30387              4        ApplicationCosmosAsyncRepositoryV2.GetAsync(applicationId:$bc21f6c0-772c-4863-90be-5bfce8ded826$) START
2024-10-01T12:11:28.502 …ries.ApplicationCosmosAsyncRepositoryV2 DBUG c81e69d7200a66755d8b04859fb30387              5          BaseCosmosDBDataRetriever.GetFirstDocumentOrderedAsync(TValue:ApplicationDocument) START
2024-10-01T12:11:28.505 …ries.ApplicationCosmosAsyncRepositoryV2 DBUG c81e69d7200a66755d8b04859fb30387 .090m        5           CosmosDB query for class 'ABB.EDCS.Persistence.Azure.Storage.Documents.ApplicationDocument' in database https://elsdk-acd-stage-01.documents.azure.com/, collection 'app'
2024-10-01T12:11:28.509 …ries.ApplicationCosmosAsyncRepositoryV2 TRCE c81e69d7200a66755d8b04859fb30387 .208m        5           Query: {"query":"SELECT TOP 1 VALUE root FROM root WHERE (((root[\"ApplicationId\"] = \"bc21f6c0-772c-4863-90be-5bfce8ded826\") AND (root[\"Type\"] = \"application\")) AND (root[\"DeletedDateTime\"] = null))"}
2024-10-01T12:11:28.515 Diginsight.Diagnostics.$Activity         DBUG c81e69d7200a66755d8b04859fb30387              6            Operation.Typed FeedIterator ReadNextAsync START
2024-10-01T12:11:28.789 Diginsight.Diagnostics.$Activity         DBUG c81e69d7200a66755d8b04859fb30387 .101m  274m  6            Operation.Typed FeedIterator ReadNextAsync END
2024-10-01T12:11:28.792 …ries.ApplicationCosmosAsyncRepositoryV2 DBUG c81e69d7200a66755d8b04859fb30387 .062m        5           Query executed successfully. Retrieved 1 documents of type 'ABB.EDCS.Persistence.Azure.Storage.Documents.ApplicationDocument'.
2024-10-01T12:11:28.797 …ries.ApplicationCosmosAsyncRepositoryV2 DBUG c81e69d7200a66755d8b04859fb30387 .085m  294m  5          BaseCosmosDBDataRetriever.GetFirstDocumentOrderedAsync END
2024-10-01T12:11:28.802 …ries.ApplicationCosmosAsyncRepositoryV2 DBUG c81e69d7200a66755d8b04859fb30387 .086m  320m  4        ApplicationCosmosAsyncRepositoryV2.GetAsync END
2024-10-01T12:11:40.628 …Business.Services.Devices.DeviceService DBUG c81e69d7200a66755d8b04859fb30387              4        DeviceService.GetPlantDevicesAsync(plantId:$77903d8a-ba6e-4510-b1bb-d96f415f2120$) START
2024-10-01T12:11:42.897 …ries.ApplicationCosmosAsyncRepositoryV2 DBUG c81e69d7200a66755d8b04859fb30387              5          ApplicationCosmosAsyncRepositoryV2.HasPermissionOnPlantAsync(applicationId:$bc21f6c0-772c-4863-90be-5bfce8ded826$, plantId:$77903d8a-ba6e-4510-b1bb-d96f415f2120$) START
2024-10-01T12:11:42.902 …ries.ApplicationCosmosAsyncRepositoryV2 DBUG c81e69d7200a66755d8b04859fb30387    2m        5           CosmosDB query for class 'ABB.EDCS.Persistence.Azure.Storage.Documents.ApplicationGrantDocument' in database https://elsdk-acd-stage-01.documents.azure.com/, collection 'app'
2024-10-01T12:11:42.905 …ries.ApplicationCosmosAsyncRepositoryV2 TRCE c81e69d7200a66755d8b04859fb30387 .077m        5           Query: {"query":"SELECT VALUE root FROM root WHERE ((((root[\"ApplicationId\"] = \"bc21f6c0-772c-4863-90be-5bfce8ded826\") AND (root[\"Type\"] = \"grant-plant\")) AND ((root[\"Target\"] = \"77903d8a-ba6e-4510-b1bb-d96f415f2120\") OR (root[\"Target\"] = \"00000000-0000-0000-0000-000000000000\"))) AND (root[\"DeletedDateTime\"] = null))"}
2024-10-01T12:11:43.199 …ries.ApplicationCosmosAsyncRepositoryV2 DBUG c81e69d7200a66755d8b04859fb30387 .095m  302m  5          ApplicationCosmosAsyncRepositoryV2.HasPermissionOnPlantAsync END
2024-10-01T12:11:56.585 …ge.Repositories.BIoTEquipmentRepository DBUG c81e69d7200a66755d8b04859fb30387              5          BIoTEquipmentRepository.GetPlantEquipmentsAsync(plantId:$77903d8a-ba6e-4510-b1bb-d96f415f2120$) START
2024-10-01T12:11:57.418 …ge.Repositories.BIoTEquipmentRepository DBUG c81e69d7200a66755d8b04859fb30387 .134m  833m  5          BIoTEquipmentRepository.GetPlantEquipmentsAsync ‼ END
2024-10-01T12:12:06.569 …Business.Services.Devices.DeviceService EROR c81e69d7200a66755d8b04859fb30387    2m        4         Error on retrieving the devices of the plant '77903d8a-ba6e-4510-b1bb-d96f415f2120'.
SendGrid.Helpers.Errors.Model.NotFoundException: No energy sources found for plant 77903d8a-ba6e-4510-b1bb-d96f415f2120. No default data found.
   at ABB.BIoT.Common.Pattern.Adapters.EnergySources.Implementations.PlantEnergySourcesAdapter.GetAsync(Guid plantId)
   at ABB.EDCS.Persistence.BIoT.Storage.Repositories.BIoTEquipmentRepository.GetPlantEquipmentsAsync(Guid plantId, StorageOperationContext ctx, CancellationToken cancellationToken) in E:\dev.darioa\01. ABB Port\EDCS_SDK\Sources\EdcsSdk\ABB.EDCS.Persistence.BIoT\Storage\Repositories\BIoTEquipmentRepository.cs:line 197
   at ABB.EDCS.Business.Services.Devices.DeviceService.GetPlantDevicesAsync(Guid plantId, OperationContext ctx, CancellationToken cancellationToken) in E:\dev.darioa\01. ABB Port\EDCS_SDK\Sources\EdcsSdk\ABB.EDCS.Business\Services\Devices\DeviceService.cs:line 84
2024-10-01T12:12:06.620 …Business.Services.Devices.DeviceService DBUG c81e69d7200a66755d8b04859fb30387    3m   26s  4        DeviceService.GetPlantDevicesAsync ‼ END
2024-10-01T12:12:06.624 …CS.WebAPI.Controllers.DevicesController EROR c81e69d7200a66755d8b04859fb30387 .127m        3       No energy sources found for plant 77903d8a-ba6e-4510-b1bb-d96f415f2120. No default data found.
2024-10-01T12:12:08.006 …CS.WebAPI.Controllers.DevicesController EROR c81e69d7200a66755d8b04859fb30387    3m        3       Error on InternalServerErrorWithContent
2024-10-01T12:12:08.045 …CS.WebAPI.Controllers.DevicesController DBUG c81e69d7200a66755d8b04859fb30387 .058m 39.6s  3      DevicesController.GetPlantDevicesAsync ‼ END
2024-10-01T12:12:08.051 …iddlewares.ABBContextCreationMiddleware DBUG c81e69d7200a66755d8b04859fb30387 .090m 41.1s  2    ABBContextCreationMiddleware.InvokeAsync ‼ END
2024-10-01T12:12:08.059 Diginsight.Diagnostics.$Activity         DBUG c81e69d7200a66755d8b04859fb30387    1m 41.2s  1  Microsoft.AspNetCore.Hosting.HttpRequestIn ‼ END